import { describe, expect, it } from "vitest";
import { buildRivalCampaignDirectory } from "@/engine/rivals";
import type { GameState } from "@/engine/core/types";

function makeState(): GameState {
  return {
    seed: "seed",
    currentWeek: 4,
    currentSeason: 1,
    difficulty: "standard",
    scout: {
      id: "scout-1",
      firstName: "Ava",
      lastName: "Mills",
      age: 28,
      nationality: "England",
      currentClubId: "club-1",
      specialization: "youth",
      reputation: 40,
      salary: 1000,
      attributes: {
        judgingAbility: 10,
        judgingPotential: 10,
        adaptability: 10,
        discipline: 10,
        negotiation: 10,
        dataAnalysis: 10,
        networking: 10,
        mentalResilience: 10,
        tacticalKnowledge: 10,
        youthDevelopment: 10,
        persuasion: 10,
      },
      morale: 75,
      fatigue: 10,
      managerRelationship: { managerName: "Boss", trust: 50, weeklyInteractions: 0 },
      currentContract: { clubId: "club-1", yearsRemaining: 2, salary: 1000, bonuses: [] },
      careerHistory: [],
      preferredFoot: "right",
      languages: ["English"],
    },
    leagues: {
      "league-1": {
        id: "league-1",
        name: "Prime League",
        country: "England",
        clubIds: ["club-1", "club-2"],
        level: 1,
        reputation: 60,
      },
    },
    clubs: {
      "club-1": {
        id: "club-1",
        name: "FC North",
        leagueId: "league-1",
        reputation: 58,
        budget: 1000000,
        scoutingBudget: 100000,
        youthDevelopment: 60,
        finances: "stable",
        squadSize: 20,
        playerIds: ["player-1"],
        managerId: "manager-1",
        scoutingPhilosophy: "academyFirst",
      },
      "club-2": {
        id: "club-2",
        name: "Aurora CF",
        leagueId: "league-1",
        reputation: 55,
        budget: 900000,
        scoutingBudget: 90000,
        youthDevelopment: 58,
        finances: "stable",
        squadSize: 20,
        playerIds: ["player-2"],
        managerId: "manager-2",
        scoutingPhilosophy: "marketSmart",
      },
    },
    players: {
      "player-1": {
        id: "player-1",
        firstName: "Leo",
        lastName: "Grant",
        age: 19,
        nationality: "England",
        clubId: "club-1",
        contractClubId: "club-1",
        leagueId: "league-1",
        position: "CM",
        secondaryPositions: [],
        role: "boxToBox",
        currentAbility: 60,
        potentialAbility: 75,
        marketValue: 100000,
        wage: 1000,
        contractExpiry: 3,
        morale: 6,
        injured: false,
        onLoan: false,
        personalityProfile: { transferWillingness: 0.4, loyalty: 0.5, ambition: 0.5, professionalism: 0.5, adaptability: 0.5 },
        attributes: {
          firstTouch: 10, passing: 10, dribbling: 10, crossing: 10, shooting: 10, heading: 10, tackling: 10, finishing: 10,
          pace: 10, strength: 10, stamina: 10, agility: 10, jumping: 10, balance: 10,
          composure: 10, positioning: 10, workRate: 10, decisionMaking: 10, leadership: 10, anticipation: 10,
          offTheBall: 10, pressing: 10, defensiveAwareness: 10, vision: 10, marking: 10, teamwork: 10,
          injuryProneness: 10, consistency: 10, bigGameTemperament: 10, professionalism: 10,
        },
      },
    },
    fixtures: {},
    observations: {
      "obs-1": {
        id: "obs-1",
        playerId: "player-1",
        fixtureId: "fx-1",
        week: 1,
        season: 1,
        visibleAttributes: {},
        discoveredAttributes: [],
        confidence: 0.4,
        note: "Observed once",
      },
    },
    reports: {},
    scoutingCases: {},
    reportDeliveries: {},
    clubDecisions: {},
    youthRecruitmentBriefs: {},
    recommendationReviews: {},
    contacts: {
      "contact-1": {
        id: "contact-1",
        name: "Luis Ortega",
        type: "academyDirector",
        organization: "Benfica Youth",
        relationship: 52,
        reliability: 80,
        knownPlayerIds: ["player-1"],
        country: "Portugal",
        trustLevel: 55,
        loyalty: 60,
      },
      "contact-2": {
        id: "contact-2",
        name: "Marta Alves",
        type: "journalist",
        organization: "A Bola",
        relationship: 48,
        reliability: 70,
        knownPlayerIds: [],
        country: "Portugal",
        trustLevel: 50,
        loyalty: 55,
      },
    },
    accessAgreements: undefined,
    schedule: { week: 4, season: 1, activities: [null, null, null, null, null, null, null], completed: false },
    jobOffers: [],
    performanceReviews: [],
    inbox: [],
    npcScouts: {},
    npcReports: {},
    npcDelegations: {},
    territories: {
      "territory-1": {
        id: "territory-1",
        name: "Lisbon Circuit",
        country: "Portugal",
        countryKey: "Portugal",
        leagueIds: [],
        maxScouts: 2,
        assignedScoutIds: [],
      },
    },
    countries: ["England", "Portugal"],
    finances: {
      balance: 50000,
      weeklyIncome: 0,
      weeklyExpenses: 0,
      netWorth: 50000,
      reputationScore: 0,
      totalRevenue: 0,
      salaryIncome: 0,
      reportSalesRevenue: 0,
      placementFeeRevenue: 0,
      retainerRevenue: 0,
      consultingRevenue: 0,
      sellOnRevenue: 0,
      bonusRevenue: 0,
      retainerContracts: [],
      placementFeeRecords: [],
      reportListings: [],
      consultingContracts: [],
      office: { level: 1, rentWeekly: 0 },
      employees: [{
        id: "employee-1",
        name: "Niko Hansen",
        role: "analyst",
        quality: 70,
        salary: 500,
        morale: 64,
        fatigue: 10,
        hiredWeek: 1,
        hiredSeason: 1,
        reportsGenerated: [],
        experience: 1,
        weeklyLog: [],
        regionFocusWeeks: 0,
      }],
      analystReviews: [],
      lifestyle: { housing: "basic", transport: "economy", wellness: "basic" },
      completedCourses: [],
      pendingRetainerOffers: [],
      pendingConsultingOffers: [],
      marketTemperature: "stable",
      activeEconomicEvents: [],
      clientRelationships: [],
      pendingEmployeeEvents: [],
      satelliteOffices: [],
      awards: [],
      loans: [],
      starterBonus: { claimed: true, amount: 0 },
    },
    narrativeEvents: [],
    activeStorylines: [],
    eventDirector: { lastMajorBeatWeek: 0, lastMajorBeatSeason: 0, quietWeeks: 0, recentSpecialEventIds: [], recentCategories: [] },
    consequenceState: {
      decisions: {},
      consequences: {},
      callbacks: {},
      effectsApplied: {},
      memories: {
        "memory-family-1": {
          id: "memory-family-1",
          stakeholder: { kind: "family", id: "family-1" },
          subject: { kind: "scout", id: "scout-1" },
          tags: ["family"],
          valence: 10,
          intensity: 50,
          salience: 50,
          visibility: "private",
          createdAt: { season: 1, week: 1 },
        },
      },
      obligations: {},
      facts: {},
      opportunityLocks: {},
      history: [],
      metrics: {},
    },
    stakeholderProfiles: undefined,
    rivalScouts: {},
    rivalOrganizationState: {
      organizations: {},
      activities: [],
      opportunities: {},
      campaignState: { campaigns: {}, history: [], processedWeekKeys: [] },
      currentPressure: { discoveryChanceMultiplier: 1, poachChanceMultiplier: 1, signingChanceMultiplier: 1, youthProgressBonus: 0 },
      processedWeekKeys: [],
    },
    unlockedTools: [],
    managerProfiles: {},
    contactIntel: {},
    unsignedYouth: {
      "uy-1": {
        id: "uy-1",
        player: {
          id: "player-u1",
          firstName: "Tiago",
          lastName: "Silva",
          age: 15,
          nationality: "Portugal",
          clubId: "club-2",
          contractClubId: "club-2",
          leagueId: "league-1",
          position: "ST",
          secondaryPositions: [],
          role: "poacher",
          currentAbility: 45,
          potentialAbility: 80,
          marketValue: 15000,
          wage: 100,
          contractExpiry: 2,
          morale: 7,
          injured: false,
          onLoan: false,
          personalityProfile: { transferWillingness: 0.5, loyalty: 0.5, ambition: 0.5, professionalism: 0.5, adaptability: 0.5 },
          attributes: {
            firstTouch: 10, passing: 10, dribbling: 10, crossing: 10, shooting: 10, heading: 10, tackling: 10, finishing: 10,
            pace: 10, strength: 10, stamina: 10, agility: 10, jumping: 10, balance: 10,
            composure: 10, positioning: 10, workRate: 10, decisionMaking: 10, leadership: 10, anticipation: 10,
            offTheBall: 10, pressing: 10, defensiveAwareness: 10, vision: 10, marking: 10, teamwork: 10,
            injuryProneness: 10, consistency: 10, bigGameTemperament: 10, professionalism: 10,
          },
        },
        visibility: 60,
        buzzLevel: 30,
        discoveredBy: ["scout-1"],
        regionId: "pt-lisbon",
        country: "Portugal",
        venueAppearances: ["schoolMatch"],
        generatedSeason: 1,
        placed: false,
        retired: false,
      },
      "uy-2": {
        id: "uy-2",
        player: {
          id: "player-u2",
          firstName: "Hidden",
          lastName: "Prospect",
          age: 15,
          nationality: "Brazil",
          clubId: "club-2",
          contractClubId: "club-2",
          leagueId: "league-1",
          position: "RW",
          secondaryPositions: [],
          role: "invertedWinger",
          currentAbility: 45,
          potentialAbility: 90,
          marketValue: 15000,
          wage: 100,
          contractExpiry: 2,
          morale: 7,
          injured: false,
          onLoan: false,
          personalityProfile: { transferWillingness: 0.5, loyalty: 0.5, ambition: 0.5, professionalism: 0.5, adaptability: 0.5 },
          attributes: {
            firstTouch: 10, passing: 10, dribbling: 10, crossing: 10, shooting: 10, heading: 10, tackling: 10, finishing: 10,
            pace: 10, strength: 10, stamina: 10, agility: 10, jumping: 10, balance: 10,
            composure: 10, positioning: 10, workRate: 10, decisionMaking: 10, leadership: 10, anticipation: 10,
            offTheBall: 10, pressing: 10, defensiveAwareness: 10, vision: 10, marking: 10, teamwork: 10,
            injuryProneness: 10, consistency: 10, bigGameTemperament: 10, professionalism: 10,
          },
        },
        visibility: 10,
        buzzLevel: 5,
        discoveredBy: [],
        regionId: "br-rio",
        country: "Brazil",
        venueAppearances: ["streetFootball"],
        generatedSeason: 1,
        placed: false,
        retired: false,
      },
    },
    placementReports: {
      "placement-1": {
        id: "placement-1",
        unsignedYouthId: "uy-1",
        targetClubId: "club-2",
        scoutId: "scout-1",
        conviction: "medium",
        qualityScore: 70,
        week: 4,
        season: 1,
      },
    },
    gutFeelings: [],
    reflectionJournal: {},
    alumniRecords: [],
    legacyScore: { total: 0, level: 1, milestones: [] },
    subRegions: {},
    youthTournaments: {
      "tour-1": {
        id: "tour-1",
        name: "Setubal Showcase",
        country: "Portugal",
        countryKey: "Portugal",
        category: "named",
        prestige: "regional",
        startWeek: 4,
        endWeek: 4,
        season: 1,
        discovered: true,
        attended: false,
        poolSizeMultiplier: 1,
        observationBonus: 0.1,
        extraAttributes: 1,
      },
      "tour-2": {
        id: "tour-2",
        name: "Hidden Event",
        country: "Brazil",
        countryKey: "Brazil",
        category: "named",
        prestige: "regional",
        startWeek: 4,
        endWeek: 4,
        season: 1,
        discovered: false,
        attended: false,
        poolSizeMultiplier: 1,
        observationBonus: 0.1,
        extraAttributes: 1,
      },
    },
    internationalAssignments: [],
    activeInternationalAssignment: null,
    retiredPlayerIds: [],
    retiredPlayers: {},
    playerMovementHistory: [],
    managerDirectives: [],
    clubResponses: [],
    transferRecords: [],
    systemFitCache: {},
    predictions: [],
    dataAnalysts: [],
    statisticalProfiles: {},
    anomalyFlags: [],
    analystReports: {},
    regionalKnowledge: {
      Portugal: {
        countryId: "Portugal",
        knowledgeLevel: 35,
        discoveredLeagues: [],
        culturalInsights: [],
        localContacts: ["contact-1"],
        scoutingEfficiency: 1,
      },
    },
    matchRatings: {},
    seasonEvents: [],
    eventChains: [],
  } as unknown as GameState;
}

describe("buildRivalCampaignDirectory", () => {
  it("includes only visible actors and locations the scout can actually know", () => {
    const directory = buildRivalCampaignDirectory(makeState());

    expect(directory.player?.map((item) => item.label)).toContain("Leo Grant");
    expect(directory.player?.map((item) => item.label)).toContain("Tiago Silva");
    expect(directory.player?.map((item) => item.label)).not.toContain("Hidden Prospect");
    expect(directory.player?.find((item) => item.label === "Leo Grant")).toMatchObject({
      playerId: "player-1",
      clubId: "club-1",
      regionId: "England",
    });

    expect(directory.journalist?.map((item) => item.label)).toContain("Marta Alves");
    expect(directory.contact?.map((item) => item.label)).toContain("Luis Ortega");
    expect(directory.contact?.map((item) => item.label)).not.toContain("Marta Alves");

    expect(directory.employee?.map((item) => item.label)).toContain("Niko Hansen");
    expect(directory.family?.map((item) => item.label)).toContain("A prospect's family");

    expect(directory.venue?.map((item) => item.label)).toContain("Setubal Showcase");
    expect(directory.venue?.map((item) => item.label)).not.toContain("Hidden Event");

    expect(directory.territory?.map((item) => item.label)).toContain("Lisbon Circuit");
    expect(directory.territory?.map((item) => item.label)).toContain("Portugal");
  });
});
