import type { RNG } from "@/engine/rng";
import type {
  Club,
  ClubDecisionOutcome,
  JudgmentCategory,
  Observation,
  Player,
  PlayerRole,
  Scout,
  ScoutReport,
  YouthRecruitmentBrief,
} from "@/engine/core/types";
import {
  generateAcademyRecruitmentBriefs,
  type AcademyRecruitmentBrief,
} from "./recruitmentBriefs";
import { evaluatePresentationStrategy } from "@/engine/reports/presentationStrategy";
import { evaluateStakeholderMemoryPolicy } from "@/engine/consequences/stakeholderMemoryPolicy";
import type { ConsequenceEngineState, GameDate } from "@/engine/consequences/types";
import {
  deriveBriefRecruitmentIdentity,
  deriveClubRecruitmentIdentity,
  deriveRegionRecruitmentIdentity,
  evaluateRecruitmentIdentityFit,
} from "@/engine/world/recruitmentIdentity";
import type { ClubRecruitmentIdentity } from "@/engine/world/recruitmentIdentity";
import { resolveScoutPerkModifiers } from "@/engine/specializations/perks";
import type { YouthMobilityAssessment } from "./youthMobility";

const ROLE_BY_POSITION: Record<Player["position"], PlayerRole> = {
  GK: "sweeper",
  CB: "ballPlayingDefender",
  LB: "wingBack",
  RB: "wingBack",
  CDM: "deepLyingPlaymaker",
  CM: "boxToBox",
  CAM: "advancedPlaymaker",
  LW: "insideForward",
  RW: "insideForward",
  ST: "pressingForward",
};

function clamp(value: number): number {
  return Math.max(0, Math.min(100, Math.round(value)));
}

export const BASE_YOUTH_RECRUITMENT_BRIEF_CAPACITY = 12;
export const MINIMUM_YOUTH_RECRUITMENT_BRIEF_CAPACITY = 6;

/** One authority for initial generation, weekly refresh, and invariant checks. */
export function deriveYouthRecruitmentBriefCapacity(
  opportunityMultiplier = 1,
): number {
  const safeMultiplier = Number.isFinite(opportunityMultiplier)
    ? Math.max(0.6, Math.min(1.75, opportunityMultiplier))
    : 1;
  return Math.max(
    MINIMUM_YOUTH_RECRUITMENT_BRIEF_CAPACITY,
    Math.round(BASE_YOUTH_RECRUITMENT_BRIEF_CAPACITY * safeMultiplier),
  );
}

interface PressureTrackedYouthRecruitmentBrief extends YouthRecruitmentBrief {
  /** Stable baseline makes weekly pressure advancement replay-safe. */
  initialCompetitionPressure: number;
}

function inferredInitialCompetitionPressure(brief: YouthRecruitmentBrief): number {
  const priorityBase = {
    highCeiling: 35,
    earlyReadiness: 45,
    character: 30,
    resale: 38,
  }[brief.developmentPriority];
  const riskAdjustment = { low: 5, medium: 3, high: 0 }[brief.riskTolerance];
  return clamp(priorityBase + riskAdjustment);
}

function mapBrief(
  source: AcademyRecruitmentBrief,
  club: Club,
  identity?: ClubRecruitmentIdentity,
): PressureTrackedYouthRecruitmentBrief {
  const developmentPriority = identity?.seasonalFocus ?? source.developmentPriority;
  const riskTolerance = identity?.doctrine.riskTolerance ?? source.riskTolerance;
  const competitionPressure = clamp(
    (source.priority === "critical" ? 55 : source.priority === "high" ? 38 : 24)
    + club.reputation * 0.2
    + ((identity?.region?.competitionIntensity ?? 50) - 50) * 0.2,
  );
  return {
    // Keep the strict causal fields generated by the academy brief authority.
    // The broader YouthRecruitmentBrief surface remains the UI contract, but
    // placement settlement must not lose age, position, or evidence gates.
    ...source,
    id: source.id,
    clubId: source.clubId,
    type: "academyPlacement",
    createdWeek: source.issuedWeek,
    createdSeason: source.issuedSeason,
    expiresWeek: source.expiresWeek,
    expiresSeason: source.expiresSeason,
    requiredPositions: [source.targetPosition],
    preferredRole: ROLE_BY_POSITION[source.targetPosition],
    developmentPriority,
    maxAge: source.ageRange[1],
    riskTolerance,
    weeklyWageBudget: Math.max(
      150,
      Math.min(5_000, Math.round(club.budget / 50_000 / 50) * 50),
    ),
    competitionPressure,
    initialCompetitionPressure: competitionPressure,
    status: source.status,
  };
}

/** Generate a bounded, varied set of persisted briefs without reading hidden ability. */
export function generateYouthRecruitmentBriefs(
  rng: RNG,
  clubs: Club[],
  players: Record<string, Player>,
  week: number,
  season: number,
  existing: Record<string, YouthRecruitmentBrief> = {},
  maximumOpen = 12,
  seasonLength = 38,
  rootSeed = `academy-briefs-s${season}`,
): YouthRecruitmentBrief[] {
  const open = Object.values(existing).filter((brief) => brief.status === "open");
  let slots = Math.max(0, maximumOpen - open.length);
  if (slots === 0) return [];
  const occupiedClubIds = new Set(open.map((brief) => brief.clubId));
  // Index ownership once. Deriving every identity from the full world player
  // record would otherwise turn weekly opportunity refresh into O(clubs * players).
  const playersByClub = new Map<string, Record<string, Player>>();
  for (const player of Object.values(players)) {
    const ownerClubId = player.contractClubId ?? player.clubId;
    if (!ownerClubId) continue;
    const ownedPlayers = playersByClub.get(ownerClubId) ?? {};
    ownedPlayers[player.id] = player;
    playersByClub.set(ownerClubId, ownedPlayers);
  }
  const regionIdentities = new Map<string, ReturnType<typeof deriveRegionRecruitmentIdentity>>();
  for (const regionId of [...new Set(clubs.map((club) => club.leagueId))].sort()) {
    const regionClubs = clubs.filter((club) => club.leagueId === regionId);
    const regionPlayers = Object.fromEntries(regionClubs.flatMap((club) =>
      Object.entries(playersByClub.get(club.id) ?? {})
    ));
    regionIdentities.set(regionId, deriveRegionRecruitmentIdentity({
      regionId,
      clubs: regionClubs,
      players: regionPlayers,
      seed: rootSeed,
      season,
    }));
  }
  const candidates = [...clubs]
    .sort((left, right) => left.id.localeCompare(right.id))
    .filter((club) => !occupiedClubIds.has(club.id))
    .map((club) => ({
      club,
      identity: deriveClubRecruitmentIdentity({
        club,
        players: playersByClub.get(club.id) ?? {},
        seed: rootSeed,
        season,
        region: regionIdentities.get(club.leagueId),
      }),
      tie: rng.next(),
    }))
    .sort((left, right) =>
      right.identity.opportunityScore - left.identity.opportunityScore
      || right.club.youthAcademyRating - left.club.youthAcademyRating
      || right.tie - left.tie
      || left.club.id.localeCompare(right.club.id)
    );
  const generated: YouthRecruitmentBrief[] = [];
  for (const { club, identity } of candidates) {
    if (slots <= 0) break;
    const [brief] = generateAcademyRecruitmentBriefs(
      rng,
      club,
      players,
      week,
      season,
      { maxActiveBriefs: 1, seasonLength },
    );
    if (!brief) continue;
    generated.push(mapBrief(brief, club, identity));
    slots--;
  }
  return generated;
}

export function advanceYouthRecruitmentBriefs(
  briefs: Record<string, YouthRecruitmentBrief>,
  currentWeek: number,
  currentSeason: number,
  seasonLength = 38,
  maximumOpen = Number.POSITIVE_INFINITY,
): {
  briefs: Record<string, YouthRecruitmentBrief>;
  expiredIds: string[];
} {
  const expiredIds: string[] = [];
  const updated = Object.fromEntries(Object.values(briefs).map((brief) => {
    if (brief.status !== "open") return [brief.id, brief];
    const due = currentSeason > brief.expiresSeason
      || (currentSeason === brief.expiresSeason && currentWeek >= brief.expiresWeek);
    if (due) {
      expiredIds.push(brief.id);
      return [brief.id, { ...brief, status: "expired" as const }];
    }
    const elapsedWeeks = Math.max(
      0,
      (currentSeason - brief.createdSeason) * seasonLength
      + currentWeek - brief.createdWeek,
    );
    const tracked = brief as YouthRecruitmentBrief & {
      initialCompetitionPressure?: number;
    };
    const initialPressure = tracked.initialCompetitionPressure
      ?? inferredInitialCompetitionPressure(brief);
    const competitionPressure = clamp(Math.max(
      brief.competitionPressure,
      initialPressure + elapsedWeeks * 3,
    ));
    if (competitionPressure === brief.competitionPressure) return [brief.id, brief];
    return [brief.id, {
      ...brief,
      competitionPressure,
    }];
  })) as Record<string, YouthRecruitmentBrief>;

  // World conditions can contract the live opportunity market after briefs
  // were created. Keep the highest-pressure, nearest-deadline work and close
  // the overflow deterministically so the advertised capacity remains true.
  if (Number.isFinite(maximumOpen)) {
    const capacity = Math.max(0, Math.floor(maximumOpen));
    const active = Object.values(updated)
      .filter((brief) => brief.status === "open")
      .sort((left, right) =>
        right.competitionPressure - left.competitionPressure
        || left.expiresSeason - right.expiresSeason
        || left.expiresWeek - right.expiresWeek
        || left.createdSeason - right.createdSeason
        || left.createdWeek - right.createdWeek
        || left.id.localeCompare(right.id)
      );
    for (const brief of active.slice(capacity)) {
      updated[brief.id] = { ...brief, status: "expired" };
      expiredIds.push(brief.id);
    }
  }
  return { briefs: updated, expiredIds };
}

export interface AcademyDecisionScore {
  outcome: ClubDecisionOutcome;
  reasons: string[];
  requestedEvidenceCategory?: JudgmentCategory;
  breakdown: NonNullable<import("@/engine/core/types").ClubDecision["scoreBreakdown"]>;
}

const CONFIDENCE_SCORE = { low: 35, medium: 68, high: 92 } as const;
const CONVICTION_SCORE = { note: 20, recommend: 55, strongRecommend: 78, tablePound: 94 } as const;

function scoreWageCredibility(wage: number | undefined, budget: number): number {
  if (!Number.isFinite(wage) || !wage || wage <= 0 || budget <= 0) return 0;
  const credibleFloor = Math.max(50, Math.round(budget * 0.15));
  if (wage < credibleFloor) {
    // An implausibly cheap estimate is uncertainty, not free affordability.
    return clamp(35 + (wage / credibleFloor) * 65);
  }
  if (wage <= budget) {
    const credibleSpan = Math.max(1, budget - credibleFloor);
    return clamp(80 + ((budget - wage) / credibleSpan) * 20);
  }
  return clamp((budget / wage) * 80);
}

/**
 * Resolve a club response entirely from the authored artifact and observable
 * context. Player current ability and potential ability are intentionally not
 * accepted by the function, preventing a truth leak into recruitment logic.
 */
export function scoreAcademyClubDecision(input: {
  rng: RNG;
  report: ScoutReport;
  brief: YouthRecruitmentBrief;
  player: Pick<Player, "id" | "age" | "position" | "secondaryPositions">;
  observations: Observation[];
  scout: Scout;
  club: Club;
  relationshipScore?: number;
  placementStrategy?: {
    pitchPosture?: import("@/engine/core/types").PlacementPitchPosture;
    supportCondition?: import("@/engine/core/types").PlacementSupportCondition;
  };
  stakeholderContext?: {
    consequenceState: Pick<ConsequenceEngineState, "memories" | "obligations">;
    now: GameDate;
    seasonLength?: number;
  };
  worldConditionContext?: {
    scoreAdjustment: number;
    label: string;
  };
  mobilityAssessment?: Pick<
    YouthMobilityAssessment,
    | "status"
    | "clubDecisionAdjustment"
    | "visibleReasons"
    | "suggestedMitigationActions"
  > & Partial<Pick<YouthMobilityAssessment, "dimensions">>;
}): AcademyDecisionScore {
  const { report, brief, player, observations } = input;
  const perkModifiers = resolveScoutPerkModifiers(input.scout);
  const verdictEntries = Object.entries(report.categoryVerdicts ?? {}) as Array<[
    JudgmentCategory,
    NonNullable<NonNullable<ScoutReport["categoryVerdicts"]>[JudgmentCategory]>,
  ]>;
  const independentEvidenceCount = report.evidenceAssessment
    ? new Set(report.evidenceAssessment.claims.flatMap((claim) => claim.evidenceIds)).size
    : new Set(verdictEntries.flatMap(([, verdict]) => verdict.hypothesisIds)).size;
  const contexts = new Set(observations.map((observation) => observation.context)).size;
  const confidenceCap = clamp(
    35
    + Math.min(35, observations.length * 7)
    + Math.min(18, contexts * 6)
    + Math.min(8, independentEvidenceCount * 2),
  );
  const effectiveConfidenceByCategory = new Map<JudgmentCategory, number>();
  let declaredConfidenceTotal = 0;
  let effectiveConfidenceTotal = 0;
  for (const [category, verdict] of verdictEntries) {
    const declared = CONFIDENCE_SCORE[verdict.confidence];
    const effective = Math.min(declared, confidenceCap);
    declaredConfidenceTotal += declared;
    effectiveConfidenceTotal += effective;
    effectiveConfidenceByCategory.set(category, effective);
  }
  const confidenceAverage = verdictEntries.length > 0
    ? effectiveConfidenceTotal / verdictEntries.length
    : 20;
  const declaredConfidenceAverage = verdictEntries.length > 0
    ? declaredConfidenceTotal / verdictEntries.length
    : 20;
  const overconfidenceGap = Math.max(0, declaredConfidenceAverage - confidenceAverage);
  const calibration = clamp(100 - overconfidenceGap * 2.5);
  let evidence = clamp(
    confidenceAverage * 0.7
    + Math.min(15, independentEvidenceCount * 4)
    + Math.min(15, contexts * 5),
  );

  const positionMatch = brief.requiredPositions.includes(player.position)
    || player.secondaryPositions.some((position) => brief.requiredPositions.includes(position));
  const roleMatch = !brief.preferredRole || brief.preferredRole === report.projectedRole;
  const ageMatch = player.age <= brief.maxAge;
  const actionFit = brief.developmentPriority === "earlyReadiness"
    ? report.recommendedAction === "offerAcademyPlace"
    : report.recommendedAction !== "monitor";
  let briefFit = clamp(
    (positionMatch ? 45 : 0)
    + (roleMatch ? 25 : 8)
    + (ageMatch ? 15 : 0)
    + (actionFit ? 15 : 5),
  );
  const recruitmentIdentityFit = evaluateRecruitmentIdentityFit({
    identity: deriveBriefRecruitmentIdentity(input.club, brief),
    candidate: player,
    report,
    brief,
    observationContextCount: contexts,
  });
  briefFit = clamp(briefFit + recruitmentIdentityFit.adjustment);

  const wage = report.estimatedWeeklyWage;
  const affordability = scoreWageCredibility(wage, brief.weeklyWageBudget);
  let conviction: number = CONVICTION_SCORE[report.conviction];
  const lowConfidenceCount = verdictEntries.filter(([, verdict]) =>
    verdict.confidence === "low"
  ).length;
  const distinctRiskCount = report.riskAssessments
    ? new Set(
        report.riskAssessments
          .filter((assessment) => assessment.id !== "noMaterialSignal")
          .map((assessment) => assessment.id),
      ).size
    : new Set(
        (report.riskFactors ?? []).map((riskFactor) => riskFactor.trim().toLowerCase()).filter(Boolean),
      ).size;
  const acknowledgedUncertaintyCount = verdictEntries.filter(([, verdict]) =>
    verdict.acknowledgedUncertainty.trim().length >= 4
  ).length;
  let risk = clamp(
    42
    + Math.min(24, distinctRiskCount * 8)
    + acknowledgedUncertaintyCount * 4
    - lowConfidenceCount * 4
    - overconfidenceGap * 0.8,
  );
  if (report.conviction === "tablePound" && evidence < 68) risk = clamp(risk - 25);
  if (report.conviction === "tablePound" && overconfidenceGap >= 12) {
    conviction = clamp(conviction - Math.min(24, overconfidenceGap));
  }
  const presentationImpact = evaluatePresentationStrategy({
    approach: report.presentationApproach,
    intendedAudience: report.intendedAudience,
    brief,
    contextCount: contexts,
    // The presentation API keeps its legacy field name for save compatibility;
    // structured reports feed it independent, traceable evidence instead.
    hypothesisCount: independentEvidenceCount,
    riskFactorCount: report.riskAssessments
      ? report.riskAssessments.filter((assessment) => assessment.id !== "noMaterialSignal").length
      : report.riskFactors?.length ?? 0,
    roleMatch,
  });
  evidence = clamp(evidence + presentationImpact.adjustments.evidence);
  briefFit = clamp(briefFit + presentationImpact.adjustments.briefFit);
  risk = clamp(risk + presentationImpact.adjustments.risk);
  conviction = clamp(conviction + presentationImpact.adjustments.conviction);
  let relationship = clamp(
    (input.relationshipScore ?? 35) * 0.55 + input.scout.reputation * 0.45,
  );
  const stakeholderMemory = input.stakeholderContext
    ? evaluateStakeholderMemoryPolicy({
        memories: input.stakeholderContext.consequenceState.memories,
        obligations: input.stakeholderContext.consequenceState.obligations,
        stakeholder: { kind: "club", id: input.club.id },
        subject: { kind: "scout", id: input.scout.id },
        now: input.stakeholderContext.now,
        seasonLength: input.stakeholderContext.seasonLength,
        domain: "academyReport",
      })
    : undefined;
  if (stakeholderMemory) {
    relationship = clamp(relationship + stakeholderMemory.scoreAdjustment);
    // Prior process trust informs the club's view of disclosed report risk,
    // but at half strength so memory cannot overpower current evidence.
    risk = clamp(risk + Math.round(stakeholderMemory.scoreAdjustment * 0.5));
  }
  const pressureDirection = report.conviction === "strongRecommend" || report.conviction === "tablePound"
    ? 1
    : -0.45;
  const competition = clamp(50 + (brief.competitionPressure - 50) * pressureDirection);
  const seasonalRecruitmentAdjustment = Math.max(
    -12,
    Math.min(12, Math.round(input.worldConditionContext?.scoreAdjustment ?? 0)),
  );
  const placementReputationAdjustment = Math.round(
    perkModifiers.placementReputationBonus * 20,
  );
  const mobilityAdjustment = Math.max(
    -12,
    Math.min(3, Math.round(input.mobilityAssessment?.clubDecisionAdjustment.score ?? 0)),
  );
  const placementStrategyProvided = input.placementStrategy !== undefined;
  const pitchPosture = input.placementStrategy?.pitchPosture ?? "evidenceLed";
  const supportCondition = input.placementStrategy?.supportCondition ?? "none";
  const postureAdjustment = !placementStrategyProvided
    ? 0
    : pitchPosture === "evidenceLed"
    ? (independentEvidenceCount >= 2 && contexts >= 2 ? 4 : 1)
    : pitchPosture === "pathwayLed"
      ? (briefFit >= 70 ? 4 : 1)
      : (relationship >= 60 ? 4 : 1);
  const mobilityDimensions = input.mobilityAssessment?.dimensions;
  const supportAdjustment = supportCondition === "educationPlan"
    ? ((mobilityDimensions?.familyEducation.riskScore ?? 0) >= 35 ? 3 : 1)
    : supportCondition === "playingPathway"
      ? ((mobilityDimensions?.pathwaySupport.riskScore ?? 0) >= 35 ? 3 : 1)
      : supportCondition === "familySupport"
        ? (Math.max(
            mobilityDimensions?.familyEducation.riskScore ?? 0,
            mobilityDimensions?.adaptation.riskScore ?? 0,
          ) >= 35 ? 3 : 1)
        : 0;
  const placementStrategyAdjustment = Math.min(7, postureAdjustment + supportAdjustment);
  const total = clamp(
    evidence * 0.25
    + briefFit * 0.25
    + affordability * 0.15
    + conviction * 0.15
    + risk * 0.1
    + relationship * 0.05
    + competition * 0.05
    + presentationImpact.alignmentAdjustment
    + seasonalRecruitmentAdjustment
    + placementReputationAdjustment
    + mobilityAdjustment
    + placementStrategyAdjustment
    + (input.rng.next() - 0.5) * 8,
  );
  const breakdown = {
    evidence,
    briefFit,
    affordability,
    conviction,
    risk,
    relationship,
    competition,
    presentation: presentationImpact.presentationScore,
    calibration,
    mobility: mobilityAdjustment,
    total,
  };

  const rankedWeaknesses: Array<[JudgmentCategory, number]> = [
    "potential",
    "roleFit",
    "characterRisk",
  ].map((category) => [
    category as JudgmentCategory,
    report.categoryVerdicts?.[category as JudgmentCategory]
      ? effectiveConfidenceByCategory.get(category as JudgmentCategory) ?? 0
      : 0,
  ]);
  rankedWeaknesses.sort((left, right) => left[1] - right[1]);
  const requestedEvidenceCategory = rankedWeaknesses[0]?.[0];
  const reasons = [
    briefFit >= 75
      ? "The player closely matches the academy brief."
      : "The player only partially matches the requested profile.",
    evidence >= 70
      ? "The judgment is supported by varied, confident evidence."
      : `The club wants clearer ${requestedEvidenceCategory ?? "supporting"} evidence.`,
    affordability >= 80
      ? "The proposed wage sits inside the academy budget."
      : "The wage estimate stretches the academy budget.",
    risk >= 65
      ? "The disclosed risks are acceptable for this club."
      : "The risk profile is too exposed for the stated conviction.",
    overconfidenceGap >= 8
      ? `Declared confidence outruns the available evidence by ${Math.round(overconfidenceGap)} points.`
      : "Declared confidence is proportionate to the available evidence.",
    ...recruitmentIdentityFit.reasons,
    presentationImpact.legacyNeutral
      ? presentationImpact.reasons[0]
      : `${presentationImpact.label} presentation: evidence ${presentationImpact.adjustments.evidence >= 0 ? "+" : ""}${presentationImpact.adjustments.evidence}, brief fit ${presentationImpact.adjustments.briefFit >= 0 ? "+" : ""}${presentationImpact.adjustments.briefFit}, risk ${presentationImpact.adjustments.risk >= 0 ? "+" : ""}${presentationImpact.adjustments.risk}, conviction ${presentationImpact.adjustments.conviction >= 0 ? "+" : ""}${presentationImpact.adjustments.conviction}; room alignment ${presentationImpact.alignmentAdjustment >= 0 ? "+" : ""}${presentationImpact.alignmentAdjustment}.`,
    ...(!presentationImpact.legacyNeutral && presentationImpact.reasons.length > 0
      ? [presentationImpact.reasons[0]]
      : []),
    ...(stakeholderMemory?.reason
      ? [`${stakeholderMemory.reason} Relationship ${stakeholderMemory.scoreAdjustment >= 0 ? "+" : ""}${stakeholderMemory.scoreAdjustment}; process-risk ${Math.round(stakeholderMemory.scoreAdjustment * 0.5) >= 0 ? "+" : ""}${Math.round(stakeholderMemory.scoreAdjustment * 0.5)}.`]
      : []),
    ...(seasonalRecruitmentAdjustment !== 0
      ? [`${input.worldConditionContext?.label ?? "The seasonal recruitment climate"} ${seasonalRecruitmentAdjustment > 0 ? "increases" : "reduces"} the club's appetite to act (${seasonalRecruitmentAdjustment > 0 ? "+" : ""}${seasonalRecruitmentAdjustment}).`]
      : []),
    ...(placementReputationAdjustment > 0
      ? [`Your placement reputation adds trusted weight to the recommendation (+${placementReputationAdjustment}).`]
      : []),
    ...(input.mobilityAssessment
      ? [
          input.mobilityAssessment.clubDecisionAdjustment.summary,
          ...(input.mobilityAssessment.visibleReasons[0]
            ? [input.mobilityAssessment.visibleReasons[0]]
            : []),
          ...(input.mobilityAssessment.status === "blocked"
            && input.mobilityAssessment.suggestedMitigationActions[0]
            ? [`Required next step: ${input.mobilityAssessment.suggestedMitigationActions[0]}`]
            : []),
        ]
      : []),
    ...(placementStrategyProvided
      ? [pitchPosture === "evidenceLed"
          ? "The pitch leads with the evidence trail and the limits of the current read."
          : pitchPosture === "pathwayLed"
            ? "The pitch leads with the role and development pathway the club can offer."
            : "The pitch uses established trust to secure a fair hearing without replacing the evidence."]
      : []),
    ...(!placementStrategyProvided || supportCondition === "none"
      ? []
      : [supportCondition === "educationPlan"
          ? "The proposal includes an education plan matched to the move."
          : supportCondition === "playingPathway"
            ? "The proposal asks the club to define a credible playing pathway."
            : "The proposal includes practical family and settlement support."]),
  ];

  let outcome: ClubDecisionOutcome;
  if (input.mobilityAssessment?.status === "blocked") {
    outcome = "followUpRequested";
  } else if (report.recommendedAction === "monitor") {
    outcome = total >= 44 ? "followUpRequested" : "rejected";
  } else if (report.recommendedAction === "inviteForTrial") {
    outcome = total >= 42 ? "followUpRequested" : "rejected";
  } else if (total >= 66) {
    outcome = "accepted";
  } else if (total >= 45) {
    outcome = "followUpRequested";
  } else {
    outcome = "rejected";
  }
  return {
    outcome,
    reasons,
    requestedEvidenceCategory: outcome === "followUpRequested"
      && input.mobilityAssessment?.status !== "blocked"
      ? requestedEvidenceCategory
      : undefined,
    breakdown,
  };
}

/**
 * Legacy compatibility helper for broad brief-state updates. Accepted academy
 * placements must instead use `fulfillAcademyRecruitmentBrief` so the authored
 * case, delivery, decision, and canonical movement stay causally linked.
 */
export function fulfillYouthRecruitmentBrief(
  brief: YouthRecruitmentBrief,
  caseId: string,
  playerId: string,
): YouthRecruitmentBrief {
  if (brief.status !== "open") return brief;
  return {
    ...brief,
    status: "fulfilled",
    assignedCaseId: caseId,
    fulfilledByPlayerId: playerId,
  };
}
