import type {
  JudgmentCategory,
  PlayerAttribute,
  PlayerRole,
  ReportRiskAssessment,
  ScoutingEvidenceCard,
  StructuredReportInput,
  YouthPresentationApproach,
  YouthRecruitmentBrief,
} from "@/engine/core/types";

import type { ReportWriterStatus } from "@/components/game/reportWriterStatus";

import {
  FORMAL_CATEGORY_UNKNOWN_OPTIONS,
  getEvidenceClaimOptions,
  getEvidenceUnknownOptions,
} from "@/engine/scout/evidenceModel";

import {
  ARCHETYPE_LABELS,
} from "@/engine/players/personalityEffects";

import {
  CategoryDraft,
  DescriptorOption,
  JUDGMENT_CATEGORIES,
  MAX_STRENGTHS,
  MAX_WEAKNESSES,
  SectionNavigatorItem,
  attrLabel,
} from "./shared";

interface DraftSuggestionSummaryInput {
  draft: {
    suggestedStrengthClaims: DescriptorOption[];
    suggestedWeaknessClaims: DescriptorOption[];
  };
  strengthClaimsByDescriptor: Map<string, DescriptorOption>;
  weaknessClaimsByDescriptor: Map<string, DescriptorOption>;
}

export function buildSuggestedDescriptorDraft({
  draft,
  strengthClaimsByDescriptor,
  weaknessClaimsByDescriptor,
}: DraftSuggestionSummaryInput): {
  strengths: string[];
  weaknesses: string[];
} {
  const strengths = draft.suggestedStrengthClaims
    .slice(0, MAX_STRENGTHS)
    .map((claim) => claim.descriptor);
  const selectedStrengthAttrs = new Set(
    strengths.flatMap(
      (descriptor) =>
        strengthClaimsByDescriptor.get(descriptor)?.attributes ?? [],
    ),
  );
  const weaknesses = draft.suggestedWeaknessClaims
    .filter(
      (claim) =>
        !claim.attributes.some((attribute) =>
          selectedStrengthAttrs.has(attribute),
        ),
    )
    .slice(0, MAX_WEAKNESSES)
    .map((claim) => claim.descriptor);

  return { strengths, weaknesses };
}

interface SummaryPlayerInput {
  firstName: string;
  lastName: string;
  position: string;
  playerTraitsRevealed?: string[];
  personalityProfile?: {
    archetype: keyof typeof ARCHETYPE_LABELS;
    hiddenUntilRevealed: boolean;
    dressingRoomImpact: number;
    bigMatchModifier: number;
  };
}

interface SummaryDraftInput {
  perceivedCAStars?: number;
  perceivedPARange?: [number, number];
}

interface AutoSummaryInput {
  draft: SummaryDraftInput;
  observationsCount: number;
  player?: SummaryPlayerInput | null;
  strengths: string[];
  weaknesses: string[];
  strengthClaimsByDescriptor: Map<string, DescriptorOption>;
  weaknessClaimsByDescriptor: Map<string, DescriptorOption>;
}

function formatDescriptorSummary(
  descriptors: string[],
  claimsByDescriptor: Map<string, DescriptorOption>,
): string {
  return descriptors
    .slice(0, 2)
    .map((descriptor) => {
      const attr = claimsByDescriptor.get(descriptor)?.attributes[0];
      return attr
        ? attrLabel(attr).toLowerCase()
        : descriptor.toLowerCase().split(" - ")[0];
    })
    .join(" and ");
}

export function buildAutoGeneratedSummary({
  draft,
  observationsCount,
  player,
  strengths,
  weaknesses,
  strengthClaimsByDescriptor,
  weaknessClaimsByDescriptor,
}: AutoSummaryInput): string {
  const lines: string[] = [];

  lines.push(
    `Based on ${observationsCount} observation${observationsCount !== 1 ? "s" : ""}, ${player?.firstName} ${player?.lastName} presents as a ${draft.perceivedCAStars ? `${draft.perceivedCAStars}-star` : "developing"} ${player?.position}.`,
  );

  if (strengths.length > 0) {
    lines.push(
      `Key strengths include ${formatDescriptorSummary(strengths, strengthClaimsByDescriptor)}.`,
    );
  }
  if (weaknesses.length > 0) {
    lines.push(
      `Areas of concern: ${formatDescriptorSummary(weaknesses, weaknessClaimsByDescriptor)}.`,
    );
  }

  const revealedTraits = player?.playerTraitsRevealed ?? [];
  if (revealedTraits.length > 0) {
    const traitStrs = revealedTraits
      .slice(0, 2)
      .map((trait) =>
        trait.replace(/([A-Z])/g, " $1").trim().toLowerCase(),
      );
    lines.push(`Notable tendencies: ${traitStrs.join(", ")}.`);
  }

  if (player?.personalityProfile && !player.personalityProfile.hiddenUntilRevealed) {
    const archetypeLabel = ARCHETYPE_LABELS[player.personalityProfile.archetype];
    lines.push(`Character: ${archetypeLabel}.`);
    if (player.personalityProfile.dressingRoomImpact <= -2) {
      lines.push("Warning: potential dressing room disruption risk.");
    } else if (player.personalityProfile.dressingRoomImpact >= 2) {
      lines.push("Positive dressing room influence expected.");
    }
    if (player.personalityProfile.bigMatchModifier >= 2) {
      lines.push("Thrives in big-match scenarios.");
    } else if (player.personalityProfile.bigMatchModifier <= -1) {
      lines.push("May struggle in high-pressure fixtures.");
    }
  }

  if (draft.perceivedPARange) {
    lines.push(
      `Potential ceiling estimated at ${draft.perceivedPARange[0]}-${draft.perceivedPARange[1]} stars.`,
    );
  }

  return lines.join(" ");
}

interface BuildStructuredReportInputArgs {
  conciseOpeningMode: boolean;
  isYouthCase: boolean;
  activeBrief?: YouthRecruitmentBrief;
  projectedRole: PlayerRole | "";
  categoryDrafts: Record<JudgmentCategory, CategoryDraft>;
  initialAssessmentCards: ScoutingEvidenceCard[];
  intendedAudience: StructuredReportInput["intendedAudience"];
  presentationApproach: YouthPresentationApproach;
  recruitmentNeed: string;
  recommendedAction: StructuredReportInput["recommendedAction"];
  selectedRiskAssessments: ReportRiskAssessment[];
  estimatedWeeklyWage: number;
  verificationDeadline?: {
    week: number;
    season: number;
  };
  alternativePlayerId: string;
}

export function buildStructuredReportInput({
  conciseOpeningMode,
  isYouthCase,
  activeBrief,
  projectedRole,
  categoryDrafts,
  initialAssessmentCards,
  intendedAudience,
  presentationApproach,
  recruitmentNeed,
  recommendedAction,
  selectedRiskAssessments,
  estimatedWeeklyWage,
  verificationDeadline,
  alternativePlayerId,
}: BuildStructuredReportInputArgs): StructuredReportInput | undefined {
  if (
    conciseOpeningMode
    || !isYouthCase
    || !activeBrief
    || !projectedRole
  ) {
    return undefined;
  }

  const categoryVerdicts = JUDGMENT_CATEGORIES.reduce<
    StructuredReportInput["categoryVerdicts"]
  >((verdicts, category) => {
    const categoryDraft = categoryDrafts[category];
    const card = initialAssessmentCards.find(
      (candidate) => candidate.id === categoryDraft.evidenceCardId,
    );
    const claim = card
      ? getEvidenceClaimOptions(card).find(
          (option) => option.id === categoryDraft.claimOptionId,
        )
      : undefined;
    const unknownOptions =
      categoryDraft.status === "assessed" && card
        ? [
            ...FORMAL_CATEGORY_UNKNOWN_OPTIONS[category],
            ...getEvidenceUnknownOptions(card),
          ]
        : FORMAL_CATEGORY_UNKNOWN_OPTIONS[category];
    const unknown = unknownOptions.find(
      (option) => option.id === categoryDraft.unknownOptionId,
    );

    verdicts[category] = {
      verdict:
        categoryDraft.status === "notAssessed"
          ? "No reportable claim is being made from the available evidence."
          : claim?.statement ?? "",
      confidence: categoryDraft.confidence,
      hypothesisIds: [],
      acknowledgedUncertainty: unknown?.statement ?? "",
      status:
        categoryDraft.status === "unselected"
          ? undefined
          : categoryDraft.status,
      evidenceIds:
        categoryDraft.status === "assessed" && card ? [card.id] : [],
      classification:
        categoryDraft.status === "assessed"
          ? claim?.classification
          : undefined,
      claimSupport:
        categoryDraft.status === "assessed" ? claim?.support : undefined,
      unknownOptionId: unknown?.id,
    };
    return verdicts;
  }, {} as StructuredReportInput["categoryVerdicts"]);

  const evidenceIds = [
    ...new Set(
      Object.values(categoryVerdicts).flatMap(
        (verdict) => verdict.evidenceIds ?? [],
      ),
    ),
  ];

  return {
    briefId: activeBrief.id,
    intendedClubId: activeBrief.clubId,
    intendedAudience,
    presentationApproach,
    recruitmentNeed,
    projectedRole,
    recommendedAction,
    riskFactors: selectedRiskAssessments
      .filter((risk) => risk.id !== "noMaterialSignal")
      .map((risk) =>
        `${risk.label}${risk.status === "untested" ? " remains untested" : " observed"}`,
      ),
    estimatedWeeklyWage,
    decisionDeadlineWeek: verificationDeadline?.week ?? activeBrief.expiresWeek,
    decisionDeadlineSeason:
      verificationDeadline?.season ?? activeBrief.expiresSeason,
    categoryVerdicts,
    alternativePlayerIds: alternativePlayerId ? [alternativePlayerId] : [],
    evidenceVersion: 1,
    evidenceIds,
    riskAssessments: selectedRiskAssessments,
  };
}

interface BuildSectionNavigatorItemsArgs {
  conciseOpeningMode: boolean;
  isYouthCase: boolean;
  canSubmit: boolean;
  reportStatus: ReportWriterStatus;
  activeBriefClubName?: string;
  completedJudgmentCount: number;
  selectedRiskAssessmentsLength: number;
  riskSignalCount: number;
  privateNarrativeNote: string;
  convictionLabel: string;
}

export function buildSectionNavigatorItems({
  conciseOpeningMode,
  isYouthCase,
  canSubmit,
  reportStatus,
  activeBriefClubName,
  completedJudgmentCount,
  selectedRiskAssessmentsLength,
  riskSignalCount,
  privateNarrativeNote,
  convictionLabel,
}: BuildSectionNavigatorItemsArgs): SectionNavigatorItem[] {
  if (conciseOpeningMode) {
    const assessmentRemaining = reportStatus.countsByStep.assessment;
    return [
      {
        id: "assessment",
        targetId: "report-section-evidence",
        label: "Assessment",
        detail: canSubmit
          ? "Five decisions logged"
          : reportStatus.primaryBlocker
            ?? "Complete the five evidence decisions",
        complete: canSubmit,
        decisionsRemaining: assessmentRemaining,
      },
    ];
  }

  if (isYouthCase) {
    const briefRemaining = reportStatus.countsByStep.brief;
    const caseRemaining = reportStatus.countsByStep.case;
    const riskRemaining = reportStatus.countsByStep.risk;
    const finalRemaining = reportStatus.countsByStep.final;

    return [
      {
        id: "brief",
        targetId: "report-section-brief",
        label: "Brief",
        detail: activeBriefClubName
          ? `${activeBriefClubName} selected`
          : "Select a matching academy brief",
        complete: briefRemaining === 0,
        decisionsRemaining: briefRemaining,
      },
      {
        id: "case",
        targetId: "report-section-framing",
        label: "Build the case",
        detail:
          caseRemaining === 0
            ? `${completedJudgmentCount}/${JUDGMENT_CATEGORIES.length} defended`
            : `${caseRemaining} decision${caseRemaining === 1 ? "" : "s"} still need support`,
        complete: caseRemaining === 0,
        decisionsRemaining: caseRemaining,
      },
      {
        id: "risk",
        targetId: "report-section-risks",
        label: "Risk",
        detail:
          riskRemaining === 0 && selectedRiskAssessmentsLength > 0
            ? `${riskSignalCount > 0 ? riskSignalCount : "No"} specific risk ${riskSignalCount === 1 ? "signal" : "signals"} logged`
            : reportStatus.blockers.find((blocker) => blocker.stepId === "risk")
                ?.message ?? "Record a risk stance",
        complete: riskRemaining === 0,
        decisionsRemaining: riskRemaining,
      },
      {
        id: "final",
        targetId: "report-section-file",
        label: "Final review",
        detail: canSubmit
          ? "Ready to file"
          : `${reportStatus.totalRemaining} issue${reportStatus.totalRemaining === 1 ? "" : "s"} to resolve`,
        complete: canSubmit,
        decisionsRemaining: finalRemaining,
      },
    ];
  }

  return [
    {
      id: "final",
      targetId: "report-section-file",
      label: "Final review",
      detail: privateNarrativeNote
        ? `${convictionLabel} conviction selected`
        : reportStatus.primaryBlocker
          ?? "Add your private note and check conviction",
      complete: canSubmit,
      decisionsRemaining: reportStatus.countsByStep.final,
    },
  ];
}
