/**
 * Insight Action Implementations
 *
 * Each insight action is a special "eureka moment" that provides
 * enhanced, bounded scouting outcomes. Actions improve the quality or scope
 * of a read, but they never guarantee hidden truth.
 */

import type { RNG } from "@/engine/rng";
import type { CareerPath, Player, Scout, Contact, Specialization } from "@/engine/core/types";
import {
  CONTENT_SCHEMA_VERSION,
  defineContentPack,
  hasNonBlankString,
  type ContentValidationIssue,
} from "@/engine/content/contracts";
import { resolveCareerPathText } from "@/engine/utils/textResolution";
import { HIDDEN_ATTRIBUTES } from "@/engine/core/types";
import type { ObservationSession, PlayerMoment } from "@/engine/observation/types";
import {
  INSIGHT_ACTIONS,
  type InsightActionId,
  type InsightActionResult,
} from "@/engine/insight/types";

// =============================================================================
// CONTEXT
// =============================================================================

/**
 * All data the engine needs to execute any insight action.
 * Callers populate only the fields relevant to the action being triggered;
 * individual handlers guard against missing optional data gracefully.
 */
export interface InsightActionContext {
  /** The scout who triggered the action. */
  scout: Scout;
  /** The active observation session. */
  session: ObservationSession;
  /** Primary player the action targets (where applicable). */
  targetPlayerId?: string;
  /** Full player records used internally to produce bounded scout estimates. */
  players: Record<string, Player>;
  /** All contacts available in the current region. */
  contacts?: Record<string, Contact>;
  /** Sub-region identifier for territory-based actions. */
  subRegionId?: string;
  /** Pre-filtered list of players in the queried league (data actions). */
  leaguePlayers?: Player[];
  /** League identifier paired with `leaguePlayers`, when one is in scope. */
  leagueId?: string;
  /** Game date used to stamp durable evidence generated by the action. */
  week: number;
  season: number;
}

// =============================================================================
// NARRATIVE SYSTEM
// =============================================================================

/**
 * Returns a short prefix phrase that tunes a narrative line to the scout's
 * active specialization, giving each specialization a distinctive voice.
 *
 *  - youth:     warm, paternal, instinctive
 *  - firstTeam: analytical, professional, decisive
 *  - regional:  relationship-based, local-knowledge flavour
 *  - data:      algorithmic, pattern-recognition tone
 */
function getSpecializationFlavor(spec: Specialization): string {
  switch (spec) {
    case "youth":
      return "Something in your gut says";
    case "firstTeam":
      return "The data crystallises:";
    case "regional":
      return "Years in this territory tell you";
    case "data":
      return "The algorithm confirms:";
  }
}

/**
 * Catalogue of narrative templates keyed by action ID and specialization.
 * Each entry contains 2-3 variants; one is chosen at random by the handler.
 */
export type InsightNarrativeVariants = Record<
  Specialization | "universal",
  readonly string[]
>;

export const INSIGHT_NARRATIVES: Record<
  InsightActionId,
  InsightNarrativeVariants
> = {
  clarityOfVision: {
    universal: [
      "The noise falls away. Every touch, every movement — brutally clear.",
      "A moment of stillness. The visible cues become easier to separate from the noise.",
      "You stop chasing every possibility and make a cleaner bounded read.",
    ],
    youth: [
      "The young player's strongest visible passage snaps into focus.",
      "Your instincts quiet. The useful cue separates from the surrounding clutter.",
      "It clicks: you have a clearer question to carry into the next watch.",
    ],
    firstTeam: [
      "Signal cuts through noise. The observable attributes become easier to grade.",
      "The assessment sharpens without pretending the margin has disappeared.",
      "Professional clarity: a tighter read with the remaining doubt still visible.",
    ],
    regional: [
      "Local familiarity strips the veil. You know this type — you see him clearly.",
      "Knowing this ground so well, the player's real quality is obvious to you.",
      "You've watched hundreds of players here. This one's truth is plain.",
    ],
    data: [
      "The perceptual noise drops. The usable signal is easier to isolate.",
      "Algorithmic clarity narrows the range without turning an estimate into truth.",
      "The filter cuts in: cleaner output, with uncertainty retained.",
    ],
  },

  hiddenNature: {
    universal: [
      "You sense something beneath the surface and leave with a sharper question.",
      "The mask slips just enough for a sharper character read.",
      "What was vague is now directional, not settled.",
    ],
    youth: [
      "Every young player hides part of themselves. Tonight you narrow the question.",
      "You've learned to read the signs early. This kid gives you a stronger angle, not certainty.",
      "Underneath the potential, a clearer character signal starts to form.",
    ],
    firstTeam: [
      "Contract pressure exposes a little more than usual. You come away with a firmer read.",
      "Proven professionals still hide things. Your read narrows the live concern.",
      "The hidden architecture of his mentality — exposed.",
    ],
    regional: [
      "People around here talk. You now have a direction worth testing.",
      "Years of relationships in this region sharpen what the eye cannot prove alone.",
      "Your network has whispered. Your instinct can finally ask a better question.",
    ],
    data: [
      "Statistical outliers sometimes point inward. The pattern narrows the character question.",
      "Hidden traits leave footprints in the numbers. The algorithm surfaces a lead, not a verdict.",
      "Variance analysis flags an anomaly worth testing in another context.",
    ],
  },

  theVerdict: {
    universal: [
      "You know what the report should emphasize, and where it still needs restraint.",
      "The report writes itself — the evidence is too clear to misstate.",
      "Your pen moves with conviction, but only as far as the evidence allows.",
    ],
    youth: [
      "This kid's potential deserves a cleaner report, not a louder one.",
      "You've seen enough to sharpen the recommendation, not to skip the caveats.",
      "Parents, coaches, and directors can use this report because it stays evidence-led.",
    ],
    firstTeam: [
      "The verdict is professional-grade because it stays within the evidence lane.",
      "You lay out the case with clearer structure and cleaner support.",
      "Clear prose, clear evidence, and a conclusion that still respects uncertainty.",
    ],
    regional: [
      "Local knowledge deepens every line without pretending to close every gap.",
      "You write with the authority of someone who knows this territory and its blind spots.",
      "The report feels authentic — because it is. Every detail is earned.",
    ],
    data: [
      "Data-backed and narrative-aware. The report is sharper, not magical.",
      "Statistical rigour meets readable prose. The result is decision-useful.",
      "The algorithm supplements the eye. The output is tighter and more honest.",
    ],
  },

  secondLook: {
    universal: [
      "Out of the corner of your eye — you almost missed him entirely.",
      "There was something there. You circle back for a bounded second pass.",
      "Your peripheral read was sharper than you realised. A second look preserves the lead.",
    ],
    youth: [
      "The boy on the left. Quiet. You nearly walked past. Now he earns a better question.",
      "A flicker in your memory: that kid in the 18th minute. You go back carefully.",
      "He wasn't your focus — but he was worth focusing on. You know that now.",
    ],
    firstTeam: [
      "The analysis doubles back. Player two deserved more time than you gave him.",
      "You revisit the footage in your mind and recover a narrower, usable lead.",
      "A professional second read. The overlooked player earns bounded attention.",
    ],
    regional: [
      "Old habits: always watch the one everyone ignores. It pays off in leads, not guarantees.",
      "Local knowledge flags him. The unfocused player finally has a clearer profile.",
      "You've seen this before — the quiet one is often the real one.",
    ],
    data: [
      "A secondary data signature stands out on review. You go back to the source with limits.",
      "Pattern matching flags an anomaly in your peripheral data. Worth a narrower look.",
      "The secondary subject's metrics warrant a second analytical pass, not a leap.",
    ],
  },

  diamondInTheRough: {
    universal: [
      "Somewhere in this match, there is a lead worth pulling forward.",
      "The player worth tracking next is not always the one everyone is watching.",
      "You scan the pitch with purpose. One name leaves with you for a reason.",
    ],
    youth: [
      "Somewhere in this rabble of kids is one who merits a stronger follow-up.",
      "Every youth session has a player who earns another trip if you know how to look.",
      "Your eye catches on something real. The upside is promising, not proven.",
    ],
    firstTeam: [
      "Not the headline act — the one who quietly outperforms his surroundings.",
      "The best player here isn't wearing the armband. You've found him.",
      "Your assessment sweeps the squad. One player registers far above the rest.",
    ],
    regional: [
      "Hidden in plain sight. You know this region — you know what to look for.",
      "Local talent often goes unnoticed. Not today. Not by you.",
      "They play for no one important. But their potential is enormous.",
    ],
    data: [
      "The visible outlier stands out from every angle. This one deserves another pass.",
      "Every metric flags the same player. The model gives you a lead worth preserving.",
      "The data points to the squad's strongest follow-up candidate, not a guaranteed ceiling.",
    ],
  },

  generationalWhisper: {
    universal: [
      "You do not get this feeling often, and you still treat it as a lead.",
      "The hairs on the back of your neck. Strong instinct, still subject to evidence.",
      "You have seen talent. This one demands another look fast.",
    ],
    youth: [
      "This kid. This specific passage. It may be something that does not happen often.",
      "Your career teaches you to notice these moments without pretending they are settled.",
      "You do not tell him. You do not tell anyone yet. You verify.",
    ],
    firstTeam: [
      "The upside signal is rare enough to demand immediate verification.",
      "No complacency, no myth-making. You are looking at a lead with rare upside.",
      "Assessment held open. Signal: exceptional. Confidence: bounded.",
    ],
    regional: [
      "This territory rarely produces signals like this, which is why you verify them fast.",
      "You've watched players in this region for years. This one is different in every way.",
      "The network already has rumours. You now have a stronger lead to test.",
    ],
    data: [
      "The model flags a rare outlier. That earns a harder follow-up, not automatic certainty.",
      "Few comparables appear in the dataset. The signal is strong enough to preserve.",
      "Algorithmic confidence is high enough to prioritize the next observation.",
    ],
  },

  perfectFit: {
    universal: [
      "You see him in your club's shirt. It fits perfectly. Every role, mapped.",
      "The system and the player — they were built for each other.",
      "You close your eyes and imagine him in the starting eleven. It works.",
    ],
    youth: [
      "You see the player he will become — and the system that will make him.",
      "His profile maps to the club's needs in ways that are almost uncanny.",
      "This is not just a good player. This is the right player for this club.",
    ],
    firstTeam: [
      "Positional analysis complete. The fit grades are exceptional across the board.",
      "Every tactical requirement met. The fit data is as clean as it gets.",
      "System compatibility confirmed. This is a plug-and-play signing.",
    ],
    regional: [
      "You've placed players at this club before. This one fits better than any.",
      "The cultural fit complements the tactical fit. A rare alignment.",
      "You can already see how the manager would use him. Perfectly.",
    ],
    data: [
      "The positional fit model runs clean. Every metric maps to a club requirement.",
      "Statistical role alignment confirmed. Fit scores above 80 across all positions.",
      "Data-driven system match: the player's profile is purpose-built for this setup.",
    ],
  },

  pressureTest: {
    universal: [
      "You put him in the biggest moment you can imagine and narrow the question.",
      "The lights come on in your mind. He doesn't flinch. Or he does.",
      "You've seen pressure break better players. This gives you a sharper test plan.",
    ],
    youth: [
      "Big games expose young players. You know this boy's truth now.",
      "He'll face moments that define careers. Now you know what to test next.",
      "The fantasy scenario plays out in your mind and gives the character read more shape.",
    ],
    firstTeam: [
      "High-stakes simulation: the player's big-game response, projected with accuracy.",
      "You've watched him in big moments. The assessment is stronger, not categorical.",
      "Pressure response grade confirmed. The verdict is in.",
    ],
    regional: [
      "Players from this region carry pressure differently. You know the signs well enough to follow them.",
      "You've seen him in tight moments. Now you know exactly what they reveal.",
      "Local derbies, title deciders — you've seen how this type responds.",
    ],
    data: [
      "Pressure performance metrics cross-referenced. The pressure picture sharpens.",
      "The high-leverage data cluster isolates the variable enough to guide the next watch.",
      "Statistical pressure model confirms the assessment. Temperament score locked.",
    ],
  },

  networkPulse: {
    universal: [
      "The network lights up. Everyone has something to say. Tonight, they all say it.",
      "You make the calls. They pick up. They all pick up.",
      "A moment of connection — every contact has been waiting to talk.",
    ],
    youth: [
      "Youth football runs on whispers. Tonight every whisper reaches you.",
      "The network knows about the kids before anyone else does. You tap in.",
      "Coaches, parents, teachers — they talk. Tonight you hear all of it.",
    ],
    firstTeam: [
      "The professional network operates in bursts. Tonight is a burst.",
      "Agents, coaches, club staff — the intel flows without the usual friction.",
      "Your reputation in this world earns moments like this. The contacts deliver.",
    ],
    regional: [
      "Every contact in the region responds at once. A perfect pulse.",
      "This is why you built this network. It pays out in full tonight.",
      "The region speaks. You listen. Every piece of intel arrives cleanly.",
    ],
    data: [
      "Network graph activation: maximum. Signal-to-noise ratio: high.",
      "The human data layer synchronises. Every node returns a clean output.",
      "Contact response rate: 100%. Intel quality: above baseline. Processing.",
    ],
  },

  territoryMastery: {
    universal: [
      "You know this ground as well as you know your own home. It shows.",
      "Something crystallises. This territory is yours.",
      "Every hour spent here adds up. In this moment, it all converges.",
    ],
    youth: [
      "You've watched more youth football in this region than anyone alive.",
      "The fields, the coaches, the patterns — it is all part of you now.",
      "Mastery doesn't happen overnight. But here, right now — it arrives.",
    ],
    firstTeam: [
      "Territorial expertise confirmed. This sub-region is no longer foreign ground.",
      "Assessment fluency in this territory is now maximal. The advantage is permanent.",
      "Professional mastery crystallised. Every future visit here benefits from today.",
    ],
    regional: [
      "This is your territory. Always was. Now the map agrees.",
      "The local knowledge is bone-deep. Every future visit will reflect that.",
      "You've earned the right to call this ground yours. The mastery is real.",
    ],
    data: [
      "Sub-region data model: calibrated to elite precision. Permanent bias correction applied.",
      "The regional algorithm internalises the territory. Confidence ceiling raised.",
      "Data mastery confirmed. This territory's noise floor drops permanently.",
    ],
  },

  algorithmicEpiphany: {
    universal: [
      "The model runs clean. The strongest signals separate from the noise.",
      "A moment of mathematical clarity. The query returns a sharper shortlist.",
      "You've been waiting for this. The algorithm delivers.",
    ],
    youth: [
      "The statistical model sees what the eye misses. Young talent, uncovered.",
      "The numbers point the way. Potential, quantified cleanly.",
      "Data and instinct in perfect agreement. A rare and powerful moment.",
    ],
    firstTeam: [
      "Analytical precision rises. The query surface is unusually clean.",
      "The model runs at capacity. The output is as clean as data gets.",
      "Strong recall meets disciplined analysis. The epiphany delivers.",
    ],
    regional: [
      "Regional data combined with local knowledge. The result is unprecedented.",
      "The algorithm and the territory speak as one. A rare convergence.",
      "Data precision, earned by presence. The two reinforce each other.",
    ],
    data: [
      "Algorithmic epiphany achieved. Query noise falls and the best leads become clearer.",
      "The dataset resolves without distortion. This is what the system was built for.",
      "A disciplined query cycle controls the known variables and exposes the remaining uncertainty.",
    ],
  },

  marketBlindSpot: {
    universal: [
      "The market doesn't see what you see. That is the opportunity.",
      "Undervalued. Overlooked. Not by you.",
      "The gap between price and quality — you've found it.",
    ],
    youth: [
      "Young players are chronically mispriced. The market has missed these ones.",
      "Potential that hasn't been monetised yet. You know who to call.",
      "The academy system hasn't caught these names. Your model has.",
    ],
    firstTeam: [
      "Market inefficiency confirmed. The club can act before prices correct.",
      "The valuation gap is real and measurable. These players are available.",
      "Arbitrage opportunity identified. Professional grade, amateur pricing.",
    ],
    regional: [
      "The region is always mispriced by outsiders. You know the truth.",
      "Local market knowledge reveals the blindspot. These names are real.",
      "Under the radar. Under the market. These players are gold.",
    ],
    data: [
      "Market inefficiency model fires. Undervaluation confirmed across all metrics.",
      "The algorithm has found the arbitrage. PA-to-price ratio: exceptional.",
      "Blind spot identified. The market will correct. Move first.",
    ],
  },
};

interface InsightNarrativeDefinition {
  id: InsightActionId;
  variants: InsightNarrativeVariants;
}

const NARRATIVE_SPECIALIZATIONS: readonly (Specialization | "universal")[] = [
  "universal",
  "youth",
  "firstTeam",
  "regional",
  "data",
];

const INSIGHT_NARRATIVE_ENTRIES: readonly InsightNarrativeDefinition[] =
  INSIGHT_ACTIONS.map((action) => ({
    id: action.id,
    variants: INSIGHT_NARRATIVES[action.id],
  }));

function validateInsightNarrativeDefinition(
  definition: InsightNarrativeDefinition,
): readonly Omit<ContentValidationIssue, "packId" | "definitionId">[] {
  const issues: Array<Omit<ContentValidationIssue, "packId" | "definitionId">> = [];
  for (const specialization of NARRATIVE_SPECIALIZATIONS) {
    const variants = definition.variants[specialization];
    if (!Array.isArray(variants) || variants.length === 0) {
      issues.push({ path: `variants.${specialization}`, message: "must contain at least one narrative line" });
      continue;
    }
    if (variants.some((line) => !hasNonBlankString(line))) {
      issues.push({ path: `variants.${specialization}`, message: "must contain only non-empty narrative lines" });
    }
  }
  return issues;
}

/**
 * The active insight-action prose is authored content, not an incidental UI
 * string. Validate it alongside the action catalogue so every available
 * action keeps a usable line for every specialization.
 */
export const INSIGHT_NARRATIVE_CONTENT_PACK = defineContentPack({
  manifest: {
    id: "talentscout.insight-narratives",
    kind: "insight-narrative",
    schemaVersion: CONTENT_SCHEMA_VERSION,
    contentVersion: "insight-narratives.1",
  },
  entries: INSIGHT_NARRATIVE_ENTRIES,
  getDefinitionId: (definition) => definition.id,
  validateDefinition: validateInsightNarrativeDefinition,
});

/**
 * Selects a narrative string for an action, biased toward the scout's
 * active specialization. Falls back to "universal" if the specialization
 * doesn't have a separate entry for the action (it always does here, but the
 * pattern is defensive).
 */
function selectNarrative(
  actionId: InsightActionId,
  spec: Specialization,
  rng: RNG,
  careerPath?: CareerPath,
): string {
  const actionNarratives = INSIGHT_NARRATIVES[actionId];
  const specLines = actionNarratives[spec];
  const flavor = getSpecializationFlavor(spec);
  const line = rng.pick(specLines);
  // Blend the specialization flavor prefix into the selected line naturally.
  // If the line already starts with a strong opener, append the flavor as a
  // suffix clause rather than a prefix to avoid awkward repetition.
  return resolveCareerPathText(`${flavor} — ${line}`, careerPath);
}

// =============================================================================
// HELPER UTILITIES
// =============================================================================

/**
 * Derives the set of PlayerAttribute keys that were hinted at during the
 * current session's moment history. Used by clarityOfVision to determine
 * which attributes are "in scope" for a perfect read.
 */
function getSessionHintedAttributes(session: ObservationSession): string[] {
  const seen = new Set<string>();
  for (const phase of session.phases) {
    for (const moment of phase.moments) {
      for (const attr of moment.attributesHinted) {
        seen.add(attr);
      }
    }
  }
  return Array.from(seen);
}

/**
 * Returns all PlayerMoments from the session that belong to a given player,
 * across all phases.
 */
function getMomentsForPlayer(
  session: ObservationSession,
  playerId: string,
): PlayerMoment[] {
  const result: PlayerMoment[] = [];
  for (const phase of session.phases) {
    for (const moment of phase.moments) {
      if (moment.playerId === playerId) {
        result.push(moment);
      }
    }
  }
  return result;
}

interface SessionLeadSignal {
  playerId: string;
  momentCount: number;
  totalQuality: number;
  avgQuality: number;
  standoutCount: number;
  pressureCount: number;
  focusedPhaseCount: number;
  attributeScores: Map<string, number>;
  leadScore: number;
  overlookedScore: number;
}

function compareSignals(
  left: { playerId: string; score: number; avgQuality: number; standoutCount: number },
  right: { playerId: string; score: number; avgQuality: number; standoutCount: number },
): number {
  if (right.score !== left.score) return right.score - left.score;
  if (right.standoutCount !== left.standoutCount) return right.standoutCount - left.standoutCount;
  if (right.avgQuality !== left.avgQuality) return right.avgQuality - left.avgQuality;
  return left.playerId.localeCompare(right.playerId);
}

function collectSessionLeadSignals(session: ObservationSession): SessionLeadSignal[] {
  const focusedCounts = new Map(
    session.players.map((player) => [player.playerId, player.focusedPhases.length]),
  );
  const signals = new Map<string, {
    momentCount: number;
    totalQuality: number;
    standoutCount: number;
    pressureCount: number;
    attributeScores: Map<string, number>;
  }>();

  for (const phase of session.phases) {
    for (const moment of phase.moments) {
      const existing = signals.get(moment.playerId) ?? {
        momentCount: 0,
        totalQuality: 0,
        standoutCount: 0,
        pressureCount: 0,
        attributeScores: new Map<string, number>(),
      };
      existing.momentCount += 1;
      existing.totalQuality += moment.quality;
      if (moment.isStandout) existing.standoutCount += 1;
      if (moment.pressureContext) existing.pressureCount += 1;
      const attributeSignal = moment.quality + (moment.isStandout ? 2 : 0) + (moment.pressureContext ? 1 : 0);
      for (const attribute of moment.attributesHinted) {
        existing.attributeScores.set(
          attribute,
          (existing.attributeScores.get(attribute) ?? 0) + attributeSignal,
        );
      }
      signals.set(moment.playerId, existing);
    }
  }

  return Array.from(signals.entries())
    .map(([playerId, signal]) => {
      const focusedPhaseCount = focusedCounts.get(playerId) ?? 0;
      const avgQuality = signal.momentCount > 0 ? signal.totalQuality / signal.momentCount : 0;
      const attributeVariety = signal.attributeScores.size;
      const leadScore = Math.round(
        avgQuality * 4
        + signal.standoutCount * 5
        + signal.pressureCount * 2
        + attributeVariety * 2
        + Math.min(3, signal.momentCount),
      );
      return {
        playerId,
        momentCount: signal.momentCount,
        totalQuality: signal.totalQuality,
        avgQuality,
        standoutCount: signal.standoutCount,
        pressureCount: signal.pressureCount,
        focusedPhaseCount,
        attributeScores: signal.attributeScores,
        leadScore,
        overlookedScore: leadScore - focusedPhaseCount * 4,
      };
    })
    .sort((left, right) => compareSignals(
      {
        playerId: left.playerId,
        score: left.overlookedScore,
        avgQuality: left.avgQuality,
        standoutCount: left.standoutCount,
      },
      {
        playerId: right.playerId,
        score: right.overlookedScore,
        avgQuality: right.avgQuality,
        standoutCount: right.standoutCount,
      },
    ));
}

function getTopSignalAttributes(
  signal: SessionLeadSignal,
  limit: number,
): string[] {
  return Array.from(signal.attributeScores.entries())
    .sort((left, right) => {
      if (right[1] !== left[1]) return right[1] - left[1];
      return left[0].localeCompare(right[0]);
    })
    .slice(0, limit)
    .map(([attribute]) => attribute);
}

/**
 * Converts a WonderkidTier to a human-readable signal phrase used in
 * generationalWhisper narratives.
 */
function tierToSignalPhrase(
  tier: "generational" | "worldClass" | "qualityPro" | "journeyman",
): string {
  switch (tier) {
    case "generational":
      return "a once-in-a-generation talent";
    case "worldClass":
      return "a future world-class player";
    case "qualityPro":
      return "a quality professional";
    case "journeyman":
      return "a solid journeyman";
  }
}

function describeHiddenIntel(
  attribute: (typeof HIDDEN_ATTRIBUTES)[number],
  value: number,
): string {
  const high = value >= 12;
  switch (attribute) {
    case "injuryProneness":
      return high
        ? "Recurring fitness concerns appear more serious than the public record suggests."
        : "The private medical picture is more reassuring than the market assumes.";
    case "consistency":
      return high
        ? "Training staff describe unusually dependable week-to-week standards."
        : "People close to the player still question whether the level can be repeated consistently.";
    case "bigGameTemperament":
      return high
        ? "Those around the player trust them when the occasion becomes demanding."
        : "There are private doubts about how the player responds when the stakes rise.";
    case "professionalism":
      return high
        ? "The player is regarded internally as exceptionally diligent and coachable."
        : "Daily habits and preparation standards remain a concern behind the scenes.";
  }
}

function clampAttributeValue(value: number): number {
  return Math.max(1, Math.min(20, Math.round(value)));
}

function estimateAttributeValue(
  actualValue: number,
  confidence: number,
): number {
  const clamped = clampAttributeValue(actualValue);
  const bucketSize = confidence >= 0.8 ? 3 : confidence >= 0.7 ? 4 : 5;
  const bucketStart = Math.floor((clamped - 1) / bucketSize) * bucketSize + 1;
  const bucketEnd = Math.min(20, bucketStart + bucketSize - 1);
  return clampAttributeValue((bucketStart + bucketEnd) / 2);
}

function buildEstimatedObservation(
  playerId: string,
  attribute: string,
  actualValue: number,
  confidence: number,
): NonNullable<InsightActionResult["observations"]>[number] {
  return {
    playerId,
    attribute,
    trueValue: estimateAttributeValue(actualValue, confidence),
    confidence,
  };
}

function describeNextTest(attribute: string): string {
  switch (attribute) {
    case "injuryProneness":
      return "Verify it over a second live watch after repeated high-intensity actions and ask for a fresh fitness reference.";
    case "consistency":
      return "Compare two more sessions and check whether the same habits hold from first whistle to final phase.";
    case "bigGameTemperament":
      return "Prioritise late-game, derby, or elimination pressure before hardening the report.";
    case "professionalism":
      return "Follow with a training-ground or coach-reference session before treating the character read as settled.";
    case "composure":
      return "Watch the player immediately after a turnover or concession to see whether the decision speed holds.";
    case "leadership":
      return "Track how teammates react when the game state turns against them before drawing a strong dressing-room conclusion.";
    case "decisionMaking":
      return "Stay on the player through a faster second viewing to confirm the first read under reduced time and space.";
    case "positioning":
      return "Check the player without the ball for a full additional phase to see if the spacing repeats.";
    case "vision":
      return "Review another spell with more touches to confirm whether the passing picture keeps opening early.";
    case "firstTouch":
      return "Watch the next receiving sequence in traffic to confirm the touch survives real pressure.";
    default:
      return "Use one more focused live sample before turning the signal into certainty.";
  }
}

function buildPressureConcern(
  player: Player,
): { concern: string; nextTest: string } {
  const temperament = player.attributes.bigGameTemperament ?? 1;
  const composure = player.attributes.composure ?? 1;
  const leadership = player.attributes.leadership ?? 1;
  if (temperament <= 8 || composure <= 8) {
    return {
      concern: "pressure resistance still looks fragile when the stakes spike",
      nextTest: describeNextTest("bigGameTemperament"),
    };
  }
  if (leadership <= 8) {
    return {
      concern: "the player may carry their own game without settling the group around them",
      nextTest: describeNextTest("leadership"),
    };
  }
  return {
    concern: "the pressure profile is encouraging, but the sample is still situational rather than complete",
    nextTest: describeNextTest("composure"),
  };
}

function perceivedTierFromSignal(
  signal: SessionLeadSignal,
): "generational" | "worldClass" | "qualityPro" | "journeyman" {
  if (signal.leadScore >= 55 && signal.standoutCount >= 2 && signal.attributeScores.size >= 3) {
    return "generational";
  }
  if (signal.leadScore >= 42 && signal.standoutCount >= 1) {
    return "worldClass";
  }
  if (signal.leadScore >= 28) {
    return "qualityPro";
  }
  return "journeyman";
}

function buildVerdictSupport(
  session: ObservationSession,
  targetPlayerId?: string,
): { bonus: number; supportLabel: string; nextTest: string } {
  if (session.mode === "analysis") {
    let highlightedPoints = 0;
    let relevantPoints = 0;
    let relatedAttributes = new Set<string>();
    for (const phase of session.phases) {
      for (const point of phase.dataPoints ?? []) {
        if (targetPlayerId && point.playerId && point.playerId !== targetPlayerId) continue;
        relevantPoints += 1;
        if (point.isHighlighted) highlightedPoints += 1;
        for (const attribute of point.relatedAttributes ?? []) {
          relatedAttributes.add(attribute);
        }
      }
    }
    const evidenceScore = highlightedPoints * 3 + relatedAttributes.size * 2 + Math.min(3, relevantPoints);
    const bonus = Math.max(4, Math.min(12, 4 + Math.floor(evidenceScore / 3)));
    const supportLabel = highlightedPoints >= 2
      ? "model support is coherent enough to sharpen the write-up"
      : "model support is useful but still thin";
    const nextTest = highlightedPoints >= 2
      ? "Pair the model lead with one live follow-up before locking in a strong recommendation."
      : "Add another live or video follow-up before treating the database case as settled.";
    return { bonus, supportLabel, nextTest };
  }

  if (!targetPlayerId) {
    return {
      bonus: 4,
      supportLabel: "the draft has structure, but not enough player-specific evidence to push harder",
      nextTest: "Anchor the next report in a focused player sample before escalating conviction.",
    };
  }

  const moments = getMomentsForPlayer(session, targetPlayerId);
  const attributeSet = new Set<string>();
  let standoutCount = 0;
  let pressureCount = 0;
  let totalQuality = 0;
  for (const moment of moments) {
    totalQuality += moment.quality;
    if (moment.isStandout) standoutCount += 1;
    if (moment.pressureContext) pressureCount += 1;
    for (const attribute of moment.attributesHinted) {
      attributeSet.add(attribute);
    }
  }
  const avgQuality = moments.length > 0 ? totalQuality / moments.length : 0;
  const evidenceScore = avgQuality + attributeSet.size * 2 + standoutCount * 3 + pressureCount;
  const bonus = Math.max(4, Math.min(14, 4 + Math.floor(evidenceScore / 3)));
  if (moments.length === 0) {
    return {
      bonus: 4,
      supportLabel: "the draft can be cleaner, but it cannot outrun the lack of direct evidence",
      nextTest: "Take another focused live sample before using a strong conviction.",
    };
  }
  if (attributeSet.size >= 4 && standoutCount >= 1) {
    return {
      bonus,
      supportLabel: "the evidence base is broad enough to support a firmer report",
      nextTest: pressureCount > 0
        ? "Use the existing pressure clips in the summary, then decide whether one more follow-up is needed."
        : "If the recommendation matters financially, add one pressure-context watch before final sign-off.",
    };
  }
  return {
    bonus,
    supportLabel: "the report can be tightened, but it still needs another angle before it becomes definitive",
    nextTest: pressureCount > 0
      ? "Add one more phase on the ball to widen the evidence set."
      : "Find a pressure or late-game sample before overcommitting to the current read.",
  };
}

/**
 * Computes a 0-100 positional fit score for a given player and position.
 * The heuristic weights attributes important to each position.
 *
 * This is deliberately opinionated and simplified — the engine owns "truth"
 * about fit, and the scout's job is to discover it via perfectFit.
 */
function computePositionalFit(player: Player, position: string): number {
  const a = player.attributes;

  // Weight vectors: [attributeKey, weight (0-1)]
  const weights: Record<string, Array<[keyof typeof a, number]>> = {
    GK: [
      ["composure", 0.25],
      ["anticipation", 0.2],
      ["decisionMaking", 0.2],
      ["positioning", 0.2],
      ["jumping", 0.15],
    ],
    CB: [
      ["tackling", 0.2],
      ["heading", 0.2],
      ["defensiveAwareness", 0.2],
      ["strength", 0.15],
      ["marking", 0.15],
      ["composure", 0.1],
    ],
    LB: [
      ["pace", 0.2],
      ["crossing", 0.2],
      ["tackling", 0.15],
      ["defensiveAwareness", 0.15],
      ["stamina", 0.15],
      ["agility", 0.15],
    ],
    RB: [
      ["pace", 0.2],
      ["crossing", 0.2],
      ["tackling", 0.15],
      ["defensiveAwareness", 0.15],
      ["stamina", 0.15],
      ["agility", 0.15],
    ],
    CDM: [
      ["tackling", 0.2],
      ["positioning", 0.2],
      ["pressing", 0.15],
      ["defensiveAwareness", 0.2],
      ["passing", 0.15],
      ["workRate", 0.1],
    ],
    CM: [
      ["passing", 0.2],
      ["vision", 0.2],
      ["stamina", 0.15],
      ["decisionMaking", 0.2],
      ["workRate", 0.1],
      ["firstTouch", 0.15],
    ],
    CAM: [
      ["vision", 0.25],
      ["passing", 0.2],
      ["dribbling", 0.15],
      ["firstTouch", 0.15],
      ["decisionMaking", 0.15],
      ["offTheBall", 0.1],
    ],
    LW: [
      ["pace", 0.25],
      ["dribbling", 0.2],
      ["crossing", 0.15],
      ["finishing", 0.15],
      ["agility", 0.15],
      ["offTheBall", 0.1],
    ],
    RW: [
      ["pace", 0.25],
      ["dribbling", 0.2],
      ["crossing", 0.15],
      ["finishing", 0.15],
      ["agility", 0.15],
      ["offTheBall", 0.1],
    ],
    ST: [
      ["finishing", 0.25],
      ["shooting", 0.2],
      ["heading", 0.15],
      ["strength", 0.15],
      ["pace", 0.1],
      ["offTheBall", 0.15],
    ],
  };

  const posWeights = weights[position];
  if (!posWeights) {
    // Unknown position: return a neutral mid-range score
    return 50;
  }

  // Weighted sum normalised to 0-100.
  // Attribute values are 1-20; max weighted sum = 20 * sum(weights) = 20.
  let weightedSum = 0;
  let totalWeight = 0;
  for (const [attr, weight] of posWeights) {
    const value = a[attr] ?? 1;
    weightedSum += value * weight;
    totalWeight += weight;
  }

  const normalised = weightedSum / (20 * totalWeight);
  return Math.round(normalised * 100);
}

// =============================================================================
// INDIVIDUAL ACTION HANDLERS
// =============================================================================

function clarityOfVision(
  context: InsightActionContext,
  rng: RNG,
  fizzled: boolean,
): InsightActionResult {
  const { session, targetPlayerId, players, scout } = context;
  const narrative = selectNarrative("clarityOfVision", scout.primarySpecialization, rng, scout.careerPath);

  if (!targetPlayerId) {
    return {
      actionId: "clarityOfVision",
      success: false,
      narrative: `${narrative} — but there was no focused player to apply it to.`,
    };
  }

  const player = players[targetPlayerId];
  if (!player) {
    return {
      actionId: "clarityOfVision",
      success: false,
      narrative: `${narrative} — but the player could not be located.`,
    };
  }

  // Collect all attributes that appeared in session moments (visible scope)
  let attributeScope = getSessionHintedAttributes(session) as Array<
    keyof typeof player.attributes
  >;

  // No visible moment means there is no legitimate scope for this insight.
  if (attributeScope.length === 0) {
    return {
      actionId: "clarityOfVision",
      success: false,
      narrative: `${narrative} — but no visible passage supplied a legitimate attribute cue.`,
    };
  }

  // Clarity improves a bounded estimate; it never resolves hidden truth.
  const confidence = fizzled ? 0.68 : 0.84;
  const revealCount = fizzled
    ? Math.max(1, Math.floor(attributeScope.length / 2))
    : attributeScope.length;

  const shuffled = rng.shuffle(attributeScope).slice(0, revealCount);

  const observations = shuffled.map((attr) => buildEstimatedObservation(
    targetPlayerId,
    attr as string,
    player.attributes[attr as keyof typeof player.attributes] ?? 1,
    confidence,
  ));

  const outcomeNote = fizzled
    ? ` (fizzled — ${revealCount} of ${attributeScope.length} visible cues retained at ${Math.round(confidence * 100)}% confidence)`
    : ` — ${revealCount} visible attribute reads tightened to a bounded ${Math.round(confidence * 100)}% confidence.`;

  return {
    actionId: "clarityOfVision",
    success: !fizzled,
    narrative: narrative + outcomeNote,
    observations,
  };
}

function perfectFit(
  context: InsightActionContext,
  rng: RNG,
  fizzled: boolean,
): InsightActionResult {
  const { targetPlayerId, players, scout } = context;
  const narrative = selectNarrative("perfectFit", scout.primarySpecialization, rng, scout.careerPath);

  if (!targetPlayerId) {
    return {
      actionId: "perfectFit",
      success: false,
      narrative: `${narrative} — but no target player was specified.`,
    };
  }

  const player = players[targetPlayerId];
  if (!player) {
    return {
      actionId: "perfectFit",
      success: false,
      narrative: `${narrative} — but player data was unavailable.`,
    };
  }

  const allPositions = ["GK", "CB", "LB", "RB", "CDM", "CM", "CAM", "LW", "RW", "ST"];

  // Fizzle: only analyse 2 positions instead of all 10
  const positionsToAnalyse = fizzled
    ? rng.shuffle(allPositions).slice(0, 2)
    : allPositions;

  const systemFitData: Record<string, number> = {};
  for (const pos of positionsToAnalyse) {
    systemFitData[pos] = computePositionalFit(player, pos);
  }

  const outcomeNote = fizzled
    ? ` (fizzled — only ${positionsToAnalyse.length} positions analysed)`
    : ` — all 10 positions graded.`;

  return {
    actionId: "perfectFit",
    success: !fizzled,
    narrative: narrative + outcomeNote,
    systemFitData,
  };
}

function hiddenNatureBounded(
  context: InsightActionContext,
  rng: RNG,
  fizzled: boolean,
): InsightActionResult {
  const { targetPlayerId, players, scout } = context;
  const narrative = selectNarrative("hiddenNature", scout.primarySpecialization, rng, scout.careerPath);

  if (!targetPlayerId) {
    return {
      actionId: "hiddenNature",
      success: false,
      narrative: `${narrative} but there was no player to assess.`,
    };
  }

  const player = players[targetPlayerId];
  if (!player) {
    return {
      actionId: "hiddenNature",
      success: false,
      narrative: `${narrative} but the player data was unavailable.`,
    };
  }

  const revealCount = fizzled ? 1 : 2;
  const baseConfidence = fizzled ? 0.62 : 0.74;
  const chosen = rng.shuffle([...HIDDEN_ATTRIBUTES]).slice(0, revealCount);
  const observations = chosen.map((attribute, index) =>
    buildEstimatedObservation(
      targetPlayerId,
      attribute,
      player.attributes[attribute as keyof typeof player.attributes] ?? 1,
      Math.max(0.55, baseConfidence - index * 0.06),
    ));
  const primaryAttribute = chosen[0];
  const guidance = primaryAttribute
    ? `${describeHiddenIntel(primaryAttribute, player.attributes[primaryAttribute] ?? 1)} Next test: ${describeNextTest(primaryAttribute)}`
    : "The player remains difficult to read.";

  return {
    actionId: "hiddenNature",
    success: !fizzled,
    narrative: `${narrative} ${guidance}`.trim(),
    observations,
  };
}

function theVerdictBounded(
  context: InsightActionContext,
  rng: RNG,
  fizzled: boolean,
): InsightActionResult {
  const { scout, session, targetPlayerId } = context;
  const narrative = selectNarrative("theVerdict", scout.primarySpecialization, rng, scout.careerPath);
  const support = buildVerdictSupport(session, targetPlayerId);
  const bonus = fizzled
    ? Math.max(3, Math.min(8, support.bonus - 3))
    : support.bonus;

  return {
    actionId: "theVerdict",
    success: !fizzled,
    narrative: `${narrative} Report support settles at +${bonus} because ${support.supportLabel}. Next test: ${support.nextTest}`,
    reportQualityBonus: bonus,
  };
}

function secondLookBounded(
  context: InsightActionContext,
  rng: RNG,
  fizzled: boolean,
): InsightActionResult {
  const { session, players, scout } = context;
  const narrative = selectNarrative("secondLook", scout.primarySpecialization, rng, scout.careerPath);
  const overlookedSignals = collectSessionLeadSignals(session)
    .filter((signal) => signal.focusedPhaseCount === 0);

  if (overlookedSignals.length === 0) {
    return {
      actionId: "secondLook",
      success: false,
      narrative: `${narrative} but every player in the session was already focused on.`,
    };
  }

  const chosenSignal = overlookedSignals[0];
  const player = players[chosenSignal.playerId];
  if (!player) {
    return {
      actionId: "secondLook",
      success: false,
      narrative: `${narrative} but the player's data could not be retrieved.`,
    };
  }

  const attributes = getTopSignalAttributes(chosenSignal, fizzled ? 1 : 2) as Array<
    keyof typeof player.attributes
  >;
  if (attributes.length === 0) {
    return {
      actionId: "secondLook",
      success: false,
      narrative: `${narrative} but there were no observable moments for that player.`,
    };
  }

  const baseConfidence = fizzled ? 0.68 : 0.82;
  const observations = attributes.map((attribute, index) =>
    buildEstimatedObservation(
      chosenSignal.playerId,
      attribute as string,
      player.attributes[attribute] ?? 1,
      Math.max(0.58, baseConfidence - index * 0.08),
    ));

  return {
    actionId: "secondLook",
    success: !fizzled,
    narrative: `${narrative} Overlooked lead recovered from ${chosenSignal.momentCount} visible moments. Next test: ${describeNextTest(attributes[0] as string)}`,
    observations,
    discoveredPlayerId: chosenSignal.playerId,
  };
}

function diamondInTheRoughBounded(
  context: InsightActionContext,
  rng: RNG,
  fizzled: boolean,
): InsightActionResult {
  const { session, players, scout } = context;
  const narrative = selectNarrative("diamondInTheRough", scout.primarySpecialization, rng, scout.careerPath);
  const rankedSignals = collectSessionLeadSignals(session);
  const chosenSignal = rankedSignals.find((signal) => signal.focusedPhaseCount === 0)
    ?? rankedSignals[0];

  if (!chosenSignal) {
    return {
      actionId: "diamondInTheRough",
      success: false,
      narrative: `${narrative} but no player data was available.`,
    };
  }

  const player = players[chosenSignal.playerId];
  if (!player) {
    return {
      actionId: "diamondInTheRough",
      success: false,
      narrative: `${narrative} but the lead could not be matched to player data.`,
    };
  }

  const attributes = getTopSignalAttributes(chosenSignal, fizzled ? 1 : 2) as Array<
    keyof typeof player.attributes
  >;
  const observations = attributes.map((attribute, index) =>
    buildEstimatedObservation(
      chosenSignal.playerId,
      attribute as string,
      player.attributes[attribute] ?? 1,
      Math.max(0.6, (fizzled ? 0.66 : 0.8) - index * 0.08),
    ));
  const primaryAttribute = (attributes[0] ?? "decisionMaking") as string;

  return {
    actionId: "diamondInTheRough",
    success: !fizzled,
    narrative: `${narrative} Visible lead score ${chosenSignal.overlookedScore} keeps resurfacing around ${primaryAttribute}. Next test: ${describeNextTest(primaryAttribute)}`,
    observations,
    discoveredPlayerId: chosenSignal.playerId,
  };
}

function generationalWhisperBounded(
  context: InsightActionContext,
  rng: RNG,
  fizzled: boolean,
): InsightActionResult {
  const { session, players, scout } = context;
  const narrative = selectNarrative("generationalWhisper", scout.primarySpecialization, rng, scout.careerPath);
  const chosenSignal = collectSessionLeadSignals(session)[0];

  if (!chosenSignal || !players[chosenSignal.playerId]) {
    return {
      actionId: "generationalWhisper",
      success: false,
      narrative: `${narrative} but you could not isolate the signal.`,
    };
  }

  const tier = perceivedTierFromSignal(chosenSignal);
  const reliabilityFloor = fizzled ? 0.55 : 0.68;
  const reliabilityCeiling = fizzled ? 0.68 : 0.84;
  const reliability = Math.min(
    reliabilityCeiling,
    Math.max(reliabilityFloor, reliabilityFloor + chosenSignal.leadScore / 100),
  );
  const primaryAttribute = getTopSignalAttributes(chosenSignal, 1)[0] ?? "decisionMaking";

  return {
    actionId: "generationalWhisper",
    success: !fizzled,
    narrative: `${narrative} Reliability ${reliability.toFixed(2)} points to ${tierToSignalPhrase(tier)} around player ${chosenSignal.playerId}. Next test: ${describeNextTest(primaryAttribute)}`,
    discoveredPlayerId: chosenSignal.playerId,
    wonderkidSignal: {
      playerId: chosenSignal.playerId,
      perceivedTier: tier,
      reliability,
    },
  };
}

function pressureTestBounded(
  context: InsightActionContext,
  rng: RNG,
  fizzled: boolean,
): InsightActionResult {
  const { targetPlayerId, players, scout } = context;
  const narrative = selectNarrative("pressureTest", scout.primarySpecialization, rng, scout.careerPath);

  if (!targetPlayerId) {
    return {
      actionId: "pressureTest",
      success: false,
      narrative: `${narrative} but no target player was specified.`,
    };
  }

  const player = players[targetPlayerId];
  if (!player) {
    return {
      actionId: "pressureTest",
      success: false,
      narrative: `${narrative} but player data was unavailable.`,
    };
  }

  const attributes = fizzled
    ? ["bigGameTemperament", "composure"]
    : ["bigGameTemperament", "composure", "leadership"];
  const baseConfidence = fizzled ? 0.66 : 0.8;
  const observations = attributes.map((attribute, index) =>
    buildEstimatedObservation(
      targetPlayerId,
      attribute,
      player.attributes[attribute as keyof typeof player.attributes] ?? 1,
      Math.max(0.58, baseConfidence - index * 0.07),
    ));
  const pressureRead = buildPressureConcern(player);

  return {
    actionId: "pressureTest",
    success: !fizzled,
    narrative: `${narrative} Pressure read suggests ${pressureRead.concern}. Next test: ${pressureRead.nextTest}`,
    observations,
  };
}

function networkPulse(
  context: InsightActionContext,
  rng: RNG,
  fizzled: boolean,
): InsightActionResult {
  const { contacts, players, scout, week, season } = context;
  const narrative = selectNarrative("networkPulse", scout.primarySpecialization, rng, scout.careerPath);

  if (!contacts || Object.keys(contacts).length === 0) {
    return {
      actionId: "networkPulse",
      success: false,
      narrative: `${narrative} — but no contacts were available in this region.`,
    };
  }

  const allContacts = Object.values(contacts);
  // Sort by reliability desc so highest-quality contacts go first
  const sorted = [...allContacts].sort((a, b) => b.reliability - a.reliability);

  const contactPool = fizzled
    ? sorted.slice(0, Math.max(1, Math.floor(sorted.length / 2)))
    : sorted;

  const contactIntel = contactPool.flatMap((contact) => {
    const knownPlayers = contact.knownPlayerIds
      .map((playerId) => players[playerId])
      .filter((player): player is Player => !!player);
    if (knownPlayers.length === 0) return [];
    const player = rng.pick(knownPlayers);
    const attribute = rng.pick([...HIDDEN_ATTRIBUTES]);
    return [{
      playerId: player.id,
      attribute,
      hint: describeHiddenIntel(attribute, player.attributes[attribute]),
      reliability: Math.min(1, Math.max(0, contact.reliability / 100)),
      sourceContactId: contact.id,
      sourceName: contact.name,
      recordedWeek: week,
      recordedSeason: season,
    }];
  });

  if (contactIntel.length === 0) {
    return {
      actionId: "networkPulse",
      success: false,
      narrative: `${narrative} — your contacts responded, but none had attributable player evidence to share.`,
    };
  }

  const outcomeNote = fizzled
    ? ` (fizzled — ${contactIntel.length} of ${allContacts.length} contacts responded)`
    : ` — ${contactIntel.length} contacts responded.`;

  return {
    actionId: "networkPulse",
    success: !fizzled,
    narrative: narrative + outcomeNote,
    contactIntel,
  };
}

function territoryMastery(
  context: InsightActionContext,
  rng: RNG,
  fizzled: boolean,
): InsightActionResult {
  const { scout, subRegionId } = context;
  const narrative = selectNarrative("territoryMastery", scout.primarySpecialization, rng, scout.careerPath);

  if (!subRegionId) {
    return {
      actionId: "territoryMastery",
      success: false,
      narrative: `${narrative} — no current sub-region could be resolved.`,
    };
  }

  const bonus = fizzled ? 0.06 : 0.10;
  const regionLabel = subRegionId;

  const outcomeNote = fizzled
    ? ` (fizzled — +${Math.round(bonus * 100)}% confidence in ${regionLabel})`
    : ` — permanent +${Math.round(bonus * 100)}% confidence in ${regionLabel}.`;

  return {
    actionId: "territoryMastery",
    success: !fizzled,
    narrative: narrative + outcomeNote,
    confidenceBonus: bonus,
  };
}

function algorithmicEpiphany(
  context: InsightActionContext,
  rng: RNG,
  fizzled: boolean,
): InsightActionResult {
  const { scout, leagueId } = context;
  const narrative = selectNarrative("algorithmicEpiphany", scout.primarySpecialization, rng, scout.careerPath);

  const bonus = fizzled ? 0.6 : 1.0;

  const outcomeNote = fizzled
    ? ` (fizzled — query accuracy bonus reduced to ${bonus})`
    : ` — next database query runs at perfect accuracy (bonus: ${bonus}).`;

  return {
    actionId: "algorithmicEpiphany",
    success: !fizzled,
    narrative: narrative + outcomeNote,
    queryAccuracyBonus: bonus,
    leagueId,
  };
}

function marketBlindSpot(
  context: InsightActionContext,
  rng: RNG,
  fizzled: boolean,
): InsightActionResult {
  const { leaguePlayers, leagueId, scout } = context;
  const narrative = selectNarrative("marketBlindSpot", scout.primarySpecialization, rng, scout.careerPath);

  if (!leaguePlayers || leaguePlayers.length === 0) {
    return {
      actionId: "marketBlindSpot",
      success: false,
      narrative: `${narrative} — but no league player data was available to analyse.`,
    };
  }

  // Compute undervalue score: high PA relative to low market value
  // Normalise PA (1-200) and market value to a comparable scale.
  // A player is "undervalued" when their PA is high but their market value is low.
  const maxPA = Math.max(...leaguePlayers.map((p) => p.potentialAbility), 1);
  const maxMV = Math.max(...leaguePlayers.map((p) => p.marketValue), 1);

  const scored = leaguePlayers
    .map((player) => {
      const normPA = player.potentialAbility / maxPA; // 0-1
      const normMV = player.marketValue / maxMV; // 0-1
      // High PA + low market value = high undervalue score
      const undervalueScore = normPA - normMV;
      return { playerId: player.id, undervalueScore };
    })
    .filter((entry) => entry.undervalueScore > 0)
    .sort((a, b) => b.undervalueScore - a.undervalueScore);

  const returnCount = fizzled
    ? rng.nextInt(1, 2)
    : Math.min(5, Math.max(3, Math.floor(scored.length * 0.05)));

  const undervaluedPlayers = scored.slice(0, returnCount).map((e) => e.playerId);

  if (undervaluedPlayers.length === 0) {
    return {
      actionId: "marketBlindSpot",
      success: false,
      narrative: `${narrative} — but no undervalued players were found in this dataset.`,
    };
  }

  const outcomeNote = fizzled
    ? ` (fizzled — ${undervaluedPlayers.length} undervalued player${undervaluedPlayers.length > 1 ? "s" : ""} identified)`
    : ` — ${undervaluedPlayers.length} undervalued players identified.`;

  return {
    actionId: "marketBlindSpot",
    success: !fizzled,
    narrative: narrative + outcomeNote,
    undervaluedPlayers,
    leagueId,
  };
}

// =============================================================================
// DISPATCH TABLE
// =============================================================================

type ActionHandler = (
  context: InsightActionContext,
  rng: RNG,
  fizzled: boolean,
) => InsightActionResult;

const ACTION_HANDLERS: Record<InsightActionId, ActionHandler> = {
  clarityOfVision,
  hiddenNature: hiddenNatureBounded,
  theVerdict: theVerdictBounded,
  secondLook: secondLookBounded,
  diamondInTheRough: diamondInTheRoughBounded,
  generationalWhisper: generationalWhisperBounded,
  perfectFit,
  pressureTest: pressureTestBounded,
  networkPulse,
  territoryMastery,
  algorithmicEpiphany,
  marketBlindSpot,
};

// =============================================================================
// CENTRAL DISPATCH
// =============================================================================

/**
 * Execute an insight action and return its result.
 *
 * @param actionId   - The canonical action identifier.
 * @param context    - All engine data available for this execution.
 * @param rng        - Seeded PRNG for deterministic RNG-driven outcomes.
 * @param fizzled    - When true, the action fires at ~60% effectiveness.
 *                     IP is still spent; cooldown still applies.
 *
 * The dispatcher:
 *  1. Looks up the appropriate handler from the dispatch table.
 *  2. Calls the handler with context, rng, and the fizzle flag.
 *  3. Returns the result exactly as produced by the handler.
 *
 * Fizzle is decided externally (based on scout fatigue and an RNG check in the
 * insight system controller) and passed in here so this module stays pure.
 */
export function executeInsightAction(
  actionId: InsightActionId,
  context: InsightActionContext,
  rng: RNG,
  fizzled: boolean,
): InsightActionResult {
  const handler = ACTION_HANDLERS[actionId];
  return handler(context, rng, fizzled);
}
