/**
 * Core type definitions for the TalentScout game engine.
 *
 * This module is the canonical source of truth for every domain type in the
 * game. All other engine modules import from here — no circular dependencies.
 *
 * Design notes:
 *  - Pure TypeScript: no React or runtime framework imports.
 *  - All IDs are strings (UUIDs generated by the world-builder at game start).
 *  - Player attributes use a 1–20 scale (Football Manager convention).
 *  - Player ability uses a 1–200 scale.
 *  - All types are plain data objects (no classes, no mutable state).
 */

// =============================================================================
// ATTRIBUTE SYSTEM
// =============================================================================

export type AttributeDomain =
  | "technical"
  | "physical"
  | "mental"
  | "tactical"
  | "hidden";

export type TechnicalAttribute =
  | "firstTouch"
  | "passing"
  | "dribbling"
  | "crossing"
  | "shooting"
  | "heading";

export type PhysicalAttribute = "pace" | "strength" | "stamina" | "agility";

export type MentalAttribute =
  | "composure"
  | "positioning"
  | "workRate"
  | "decisionMaking"
  | "leadership";

export type TacticalAttribute =
  | "offTheBall"
  | "pressing"
  | "defensiveAwareness";

/**
 * Hidden attributes are not directly observable during a match.
 * Scouts must infer them over many observations or via contact tips.
 */
export type HiddenAttribute =
  | "injuryProneness"
  | "consistency"
  | "bigGameTemperament"
  | "professionalism";

export type PlayerAttribute =
  | TechnicalAttribute
  | PhysicalAttribute
  | MentalAttribute
  | TacticalAttribute
  | HiddenAttribute;

/**
 * Maps every PlayerAttribute to its AttributeDomain.
 * Used by the perception engine to determine which scout skill applies
 * when generating an observation reading.
 */
export const ATTRIBUTE_DOMAINS: Record<PlayerAttribute, AttributeDomain> = {
  // Technical
  firstTouch: "technical",
  passing: "technical",
  dribbling: "technical",
  crossing: "technical",
  shooting: "technical",
  heading: "technical",

  // Physical
  pace: "physical",
  strength: "physical",
  stamina: "physical",
  agility: "physical",

  // Mental
  composure: "mental",
  positioning: "mental",
  workRate: "mental",
  decisionMaking: "mental",
  leadership: "mental",

  // Tactical
  offTheBall: "tactical",
  pressing: "tactical",
  defensiveAwareness: "tactical",

  // Hidden — inferred over time, not directly observable in-match
  injuryProneness: "hidden",
  consistency: "hidden",
  bigGameTemperament: "hidden",
  professionalism: "hidden",
} as const;

/** Ordered list of all technical attribute keys. Useful for iteration. */
export const TECHNICAL_ATTRIBUTES: readonly TechnicalAttribute[] = [
  "firstTouch",
  "passing",
  "dribbling",
  "crossing",
  "shooting",
  "heading",
] as const;

export const PHYSICAL_ATTRIBUTES: readonly PhysicalAttribute[] = [
  "pace",
  "strength",
  "stamina",
  "agility",
] as const;

export const MENTAL_ATTRIBUTES: readonly MentalAttribute[] = [
  "composure",
  "positioning",
  "workRate",
  "decisionMaking",
  "leadership",
] as const;

export const TACTICAL_ATTRIBUTES: readonly TacticalAttribute[] = [
  "offTheBall",
  "pressing",
  "defensiveAwareness",
] as const;

export const HIDDEN_ATTRIBUTES: readonly HiddenAttribute[] = [
  "injuryProneness",
  "consistency",
  "bigGameTemperament",
  "professionalism",
] as const;

export const ALL_ATTRIBUTES: readonly PlayerAttribute[] = [
  ...TECHNICAL_ATTRIBUTES,
  ...PHYSICAL_ATTRIBUTES,
  ...MENTAL_ATTRIBUTES,
  ...TACTICAL_ATTRIBUTES,
  ...HIDDEN_ATTRIBUTES,
] as const;

// =============================================================================
// PLAYER
// =============================================================================

export type Position =
  | "GK"
  | "CB"
  | "LB"
  | "RB"
  | "CDM"
  | "CM"
  | "CAM"
  | "LW"
  | "RW"
  | "ST";

export const ALL_POSITIONS: readonly Position[] = [
  "GK",
  "CB",
  "LB",
  "RB",
  "CDM",
  "CM",
  "CAM",
  "LW",
  "RW",
  "ST",
] as const;

export type Foot = "left" | "right" | "both";

/**
 * Development profiles define the shape of a player's growth curve.
 *  - earlyBloomer:  peaks early (~age 22), declines faster than peers
 *  - lateBloomer:   slow early growth, best years from ~age 28
 *  - steadyGrower:  linear progression, reliable and predictable
 *  - volatile:      high variance — can surge or plateau unexpectedly
 */
export type DevelopmentProfile =
  | "earlyBloomer"
  | "lateBloomer"
  | "steadyGrower"
  | "volatile";

/**
 * WonderkidTier is a hidden internal classification used by the world
 * generator to seed potential ability and club transfer interest levels.
 *  - generational: PA 180–200, once-in-a-generation players
 *  - worldClass:   PA 150–179, regular full internationals at elite clubs
 *  - qualityPro:   PA 100–149, solid professionals, top flight regulars
 *  - journeyman:   PA < 100, lower divisions and squad fillers
 */
export type WonderkidTier =
  | "generational"
  | "worldClass"
  | "qualityPro"
  | "journeyman";

export interface Player {
  id: string;
  firstName: string;
  lastName: string;
  age: number;
  dateOfBirth: { day: number; month: number; year: number };
  nationality: string;
  position: Position;
  secondaryPositions: Position[];
  preferredFoot: Foot;
  clubId: string;
  /** Season year in which the player's contract expires. */
  contractExpiry: number;
  /** Weekly wage in game currency. */
  wage: number;
  /** Estimated transfer market value. */
  marketValue: number;

  /**
   * True attribute values on a 1–20 scale.
   * These are never shown directly to the player (scout); they are revealed
   * only through scouting observations with appropriate confidence intervals.
   */
  attributes: Record<PlayerAttribute, number>;

  /** Derived composite ability score, 1–200, weighted by position. */
  currentAbility: number;
  /** Hard ceiling for future growth — the maximum CA the player can ever reach. */
  potentialAbility: number;
  developmentProfile: DevelopmentProfile;
  wonderkidTier: WonderkidTier;

  /** Short-term form modifier in [-3, 3]. Positive = hot streak. */
  form: number;
  /** Morale on 1–10 scale; affects performance and transfer willingness. */
  morale: number;
  injured: boolean;
  injuryWeeksRemaining: number;
}

// =============================================================================
// CLUB & LEAGUE
// =============================================================================

/**
 * How a club approaches the transfer market and youth development.
 *  - academyFirst:    invest in youth, patient with youngsters
 *  - winNow:         high transfer spend, short-term thinking
 *  - marketSmart:    buy low / sell high, data-driven valuations
 *  - globalRecruiter: scours every continent, builds diverse squads
 */
export type ScoutingPhilosophy =
  | "academyFirst"
  | "winNow"
  | "marketSmart"
  | "globalRecruiter";

export interface Club {
  id: string;
  name: string;
  /** 3–5 character abbreviation, e.g. "MCI", "BARCA". */
  shortName: string;
  leagueId: string;
  /** Global prestige rating, 1–100. Higher = attracts better players. */
  reputation: number;
  /** Available transfer budget in game currency. */
  budget: number;
  scoutingPhilosophy: ScoutingPhilosophy;
  managerId: string;
  playerIds: string[];
  /** Quality of the youth intake system, 1–20. */
  youthAcademyRating: number;
}

export interface League {
  id: string;
  name: string;
  /** Short code, e.g. "EPL", "BL1", "LIGA". */
  shortName: string;
  country: string;
  /** 1 = top flight, 2 = second tier, etc. */
  tier: number;
  clubIds: string[];
  season: number;
}

export type Weather =
  | "clear"
  | "cloudy"
  | "rain"
  | "heavyRain"
  | "snow"
  | "windy";

export interface Fixture {
  id: string;
  homeClubId: string;
  awayClubId: string;
  leagueId: string;
  week: number;
  played: boolean;
  homeGoals?: number;
  awayGoals?: number;
  attendance?: number;
  weather?: Weather;
}

// =============================================================================
// SCOUT
// =============================================================================

/**
 * Primary specialization domains.
 *  - youth:      players under 21; better at reading potential over CA
 *  - firstTeam:  ready-now players; focus on current ability accuracy
 *  - regional:   deep knowledge of one geographic territory
 *  - data:       statistical analysis; unlocks data overlays on reports
 */
export type Specialization = "youth" | "firstTeam" | "regional" | "data";

/**
 * Scout skills — determine accuracy and depth of attribute assessments.
 *  - technicalEye:          reading technical attributes
 *  - physicalAssessment:    reading physical attributes
 *  - psychologicalRead:     reading mental and hidden attributes
 *  - tacticalUnderstanding: reading tactical attributes
 *  - dataLiteracy:          interpreting statistics (data specialization perk)
 */
export type ScoutSkill =
  | "technicalEye"
  | "physicalAssessment"
  | "psychologicalRead"
  | "tacticalUnderstanding"
  | "dataLiteracy"
  | "playerJudgment"
  | "potentialAssessment";

/**
 * Scout personal attributes that affect career mechanics.
 *  - networking:    unlocks contacts faster, improves contact quality
 *  - persuasion:    amplifies conviction level impact on club decisions
 *  - endurance:     reduces fatigue accumulation per activity
 *  - adaptability:  reduces accuracy penalty in unfamiliar regions
 *  - memory:        retains more detail from video analysis sessions
 *  - intuition:     chance of detecting hidden attributes without indicators
 */
export type ScoutAttribute =
  | "networking"
  | "persuasion"
  | "endurance"
  | "adaptability"
  | "memory"
  | "intuition";

/**
 * Career progression ladder.
 *  1 = Freelance scout (no club, self-employed)
 *  2 = Part-time regional scout
 *  3 = Full-time club scout
 *  4 = Head of scouting / chief scout
 *  5 = Director of football / sporting director
 */
export type CareerTier = 1 | 2 | 3 | 4 | 5;

export interface Scout {
  id: string;
  firstName: string;
  lastName: string;
  age: number;
  /** Scout's nationality (flavour / display field, not mechanically enforced). */
  nationality?: string;

  /** Scout skill ratings on 1–20 scale. */
  skills: Record<ScoutSkill, number>;
  /** Scout personal attribute ratings on 1–20 scale. */
  attributes: Record<ScoutAttribute, number>;

  primarySpecialization: Specialization;
  secondarySpecialization?: Specialization;
  /** Depth of mastery within the primary specialization, 1–20. */
  specializationLevel: number;
  /**
   * IDs of unlocked specialization perks.
   * Examples: "youthEye", "dataDriven", "setpieceReader", "mentorNetwork"
   */
  unlockedPerks: string[];

  careerTier: CareerTier;
  /** Global scouting reputation, 0–100. Determines job offer quality. */
  reputation: number;
  /** Trust level with current employer club, 0–100. Affects report weight. */
  clubTrust: number;
  /** Reputation within the scout's specialization community, 0–100. */
  specializationReputation: number;

  currentClubId?: string;
  contractEndSeason?: number;
  salary: number;
  savings: number;

  // Lifetime career statistics
  reportsSubmitted: number;
  successfulFinds: number;
  /** IDs of players the scout discovered before any other scout. */
  discoveryCredits: string[];

  /**
   * Fatigue level 0–100.
   * High fatigue reduces observation accuracy and report quality.
   * Recovered via rest activities or natural end-of-week recovery.
   */
  fatigue: number;

  /** Accumulated XP toward next skill level-up. Threshold = currentLevel * 10. */
  skillXp: Partial<Record<ScoutSkill, number>>;
  /** Accumulated XP toward next attribute level-up. Threshold = currentLevel * 10. */
  attributeXp: Partial<Record<ScoutAttribute, number>>;

  // --- Phase 1 extensions ---

  /** IDs of NPC scouts managed by the player (tier 4+). */
  npcScoutIds: string[];
  /** Per-country reputation tracking. */
  countryReputations: Record<string, CountryReputation>;
  /** Relationship with the current club's manager. */
  managerRelationship?: ManagerRelationship;
  /** Active board directives from the club hierarchy (tier 5). */
  boardDirectives: BoardDirective[];
  /** Current international travel booking (null if at home). */
  travelBooking?: TravelBooking;
}

// =============================================================================
// PERCEPTION & OBSERVATIONS
// =============================================================================

export type ObservationContext =
  | "liveMatch"
  | "videoAnalysis"
  | "trainingGround"
  | "youthTournament"
  | "academyVisit"
  | "schoolMatch"
  | "grassrootsTournament"
  | "streetFootball"
  | "academyTrialDay"
  | "youthFestival"
  | "followUpSession"
  | "parentCoachMeeting";

export interface FlaggedMoment {
  /** Minute or phase index when this notable moment occurred. */
  phase: number;
  description: string;
  attribute: PlayerAttribute;
  positive: boolean;
}

/**
 * A single attribute reading within one observation session.
 * Perceived value and confidence are biased by scout skill, fatigue,
 * and contextual multipliers.
 */
export interface AttributeReading {
  attribute: PlayerAttribute;
  /** Scout's estimate on 1–20 scale (may differ from true value). */
  perceivedValue: number;
  /** Certainty in this reading, 0–1. */
  confidence: number;
  /** Number of separate sessions contributing to this reading. */
  observationCount: number;
}

export interface Observation {
  id: string;
  playerId: string;
  scoutId: string;
  /** Set when context is liveMatch; references the Fixture id. */
  matchId?: string;
  week: number;
  season: number;
  context: ObservationContext;
  attributeReadings: AttributeReading[];
  /** Narrative notes generated by the perception engine. */
  notes: string[];
  flaggedMoments: FlaggedMoment[];
  abilityReading?: AbilityReading;
}

export interface AbilityReading {
  perceivedCA: number;       // 0.5-5.0 star rating
  caConfidence: number;      // 0-1
  perceivedPALow: number;   // PA range lower bound (0.5-5.0)
  perceivedPAHigh: number;  // PA range upper bound (0.5-5.0)
  paConfidence: number;     // 0-1
}

// =============================================================================
// REPORTS
// =============================================================================

/**
 * How strongly the scout recommends acquisition.
 *  - note:             "worth monitoring in future"
 *  - recommend:        "we should consider this player"
 *  - strongRecommend:  "sign this player soon"
 *  - tablePound:       "I stake my reputation — sign now"
 *                      (tablePounds are a limited career resource per season)
 */
export type ConvictionLevel =
  | "note"
  | "recommend"
  | "strongRecommend"
  | "tablePound";

export interface AttributeAssessment {
  attribute: PlayerAttribute;
  /** Scout's best point estimate of the true attribute value (1–20). */
  estimatedValue: number;
  /**
   * Confidence interval, e.g. [13, 16].
   * Narrower = higher accuracy. Width driven by observationCount and skill.
   */
  confidenceRange: [number, number];
  domain: AttributeDomain;
}

export interface ScoutReport {
  id: string;
  playerId: string;
  scoutId: string;
  submittedWeek: number;
  submittedSeason: number;

  attributeAssessments: AttributeAssessment[];
  strengths: string[];
  weaknesses: string[];
  conviction: ConvictionLevel;
  /** Free-text narrative written by the scout. */
  summary: string;
  /** ID of a known player the scout compares the subject to. */
  comparisonPlayerId?: string;
  estimatedValue: number;

  /**
   * Composite quality score 0–100.
   * Driven by scout skill, observation count, and confidence range widths.
   */
  qualityScore: number;

  /** Reputation change when this report was submitted. */
  reputationDelta?: number;

  /** Club's subsequent decision on the scouted player. */
  clubResponse?: "ignored" | "shortlisted" | "signed";
  /**
   * Retrospective accuracy rating set after a transfer completes, 0–100.
   * Compares report assessments to actual player attribute values.
   */
  postTransferRating?: number;

  /** Perceived current ability in half-star rating (0.5-5.0). */
  perceivedCAStars?: number;
  /** Perceived potential ability range in half-star ratings [low, high]. */
  perceivedPARange?: [number, number];
}

// =============================================================================
// CAREER
// =============================================================================

export interface JobOffer {
  id: string;
  clubId: string;
  tier: CareerTier;
  /** Human-readable role title, e.g. "Youth Scout", "Head of Scouting". */
  role: string;
  salary: number;
  /** Contract duration in seasons. */
  contractLength: number;
  /** Geographic territory assigned (relevant for regional roles). */
  territory?: string;
  /** Offer expires at end of this week; must accept/reject before then. */
  expiresWeek: number;
}

export interface PerformanceReview {
  season: number;
  reportsSubmitted: number;
  averageQuality: number;
  successfulRecommendations: number;
  tablePoundsUsed: number;
  tablePoundsSuccessful: number;
  reputationChange: number;
  outcome: "promoted" | "retained" | "warning" | "fired";
}

// =============================================================================
// NETWORK
// =============================================================================

export type ContactType =
  | "agent"
  | "scout"
  | "clubStaff"
  | "journalist"
  | "academyCoach"
  | "sportingDirector"
  | "grassrootsOrganizer"
  | "schoolCoach"
  | "youthAgent"
  | "academyDirector"
  | "localScout";

export interface Contact {
  id: string;
  name: string;
  type: ContactType;
  organization: string;
  /** Quality of relationship, 0–100. Higher = more willing to share info. */
  relationship: number;
  /**
   * How reliable the contact's tips are, 0–100.
   * Hidden from player initially; revealed through repeated interactions.
   */
  reliability: number;
  /** IDs of players this contact has information about. */
  knownPlayerIds: string[];
  /** Geographic region of expertise. */
  region?: string;
  /**
   * The country this contact primarily operates in.
   * Used for youth scouting intel and contact introductions.
   */
  country?: string;
  /**
   * The game week of the last interaction with this contact.
   * Used to calculate relationship decay over time.
   */
  lastInteractionWeek?: number;
}

// =============================================================================
// CONTACT INTEL
// =============================================================================

/**
 * A piece of hidden intelligence shared by a contact about a player.
 * Keyed by playerId in the `contactIntel` GameState record.
 */
export interface HiddenIntel {
  playerId: string;
  attribute: HiddenAttribute;
  /** Human-readable hint — worded as a scout's note, not a raw number. */
  hint: string;
  /**
   * 0–1: how reliable this intel is.
   * Determined by the contact's own reliability stat, not shown directly.
   */
  reliability: number;
}

// =============================================================================
// CALENDAR / SCHEDULE
// =============================================================================

export type ActivityType =
  | "attendMatch"
  | "watchVideo"
  | "writeReport"
  | "networkMeeting"
  | "trainingVisit"
  | "travel"
  | "study"
  | "rest"
  | "academyVisit"
  | "youthTournament"
  | "reviewNPCReport"
  | "managerMeeting"
  | "boardPresentation"
  | "assignTerritory"
  | "internationalTravel"
  | "schoolMatch"
  | "grassrootsTournament"
  | "streetFootball"
  | "academyTrialDay"
  | "youthFestival"
  | "followUpSession"
  | "parentCoachMeeting"
  | "writePlacementReport";

export interface Activity {
  type: ActivityType;
  /** Time cost in day-slots (1 slot = 1 day; 7 slots per week Mon–Sun). */
  slots: number;
  /** ID of the target entity: match, player, contact, etc. */
  targetId?: string;
  description: string;
}

export interface WeekSchedule {
  week: number;
  season: number;
  /**
   * 7 slots representing Monday through Sunday.
   * null = the slot is free / unscheduled.
   */
  activities: (Activity | null)[];
  completed: boolean;
}

// =============================================================================
// MATCH ENGINE
// =============================================================================

export type MatchPhaseType =
  | "buildUp"
  | "transition"
  | "setpiece"
  | "pressingSequence"
  | "counterAttack"
  | "possession";

export type MatchEventType =
  | "goal"
  | "assist"
  | "shot"
  | "pass"
  | "dribble"
  | "tackle"
  | "header"
  | "save"
  | "foul"
  | "cross"
  | "sprint"
  | "positioning"
  | "error"
  | "leadership";

export interface MatchEvent {
  minute: number;
  description: string;
  playerId: string;
  type: MatchEventType;
  /** Subjective quality of the action, 1–10. */
  quality: number;
  /** Which player attributes were made observable by this event. */
  attributesRevealed: PlayerAttribute[];
}

export interface MatchPhase {
  minute: number;
  type: MatchPhaseType;
  description: string;
  involvedPlayerIds: string[];
  events: MatchEvent[];
  /** Attributes that are generally observable during this phase type. */
  observableAttributes: PlayerAttribute[];
}

// =============================================================================
// INBOX
// =============================================================================

export type InboxMessageType =
  | "assignment"
  | "feedback"
  | "news"
  | "jobOffer"
  | "event";

export type InboxRelatedEntity = "player" | "report" | "contact" | "jobOffer" | "tool" | "narrative";

export interface InboxMessage {
  id: string;
  week: number;
  season: number;
  type: InboxMessageType;
  title: string;
  body: string;
  read: boolean;
  actionRequired: boolean;
  /** ID of the related entity: player, report, job offer, etc. */
  relatedId?: string;
  /** What kind of entity relatedId points to, enabling action buttons. */
  relatedEntityType?: InboxRelatedEntity;
}

// =============================================================================
// GAME STATE
// =============================================================================

export interface GameState {
  /** The world seed used for deterministic world generation. */
  seed: string;
  /** Current week within the season, typically 1–38. */
  currentWeek: number;
  /** Current season year, e.g. 2024. */
  currentSeason: number;

  scout: Scout;

  // World data keyed by entity ID
  leagues: Record<string, League>;
  clubs: Record<string, Club>;
  players: Record<string, Player>;
  fixtures: Record<string, Fixture>;

  // Scout's personal working data keyed by entity ID
  observations: Record<string, Observation>;
  reports: Record<string, ScoutReport>;
  contacts: Record<string, Contact>;

  /** The active week schedule. Replaced each time the week advances. */
  schedule: WeekSchedule;

  jobOffers: JobOffer[];
  performanceReviews: PerformanceReview[];

  inbox: InboxMessage[];

  // --- Phase 1 extensions ---

  /** NPC scouts managed by the player, keyed by ID. */
  npcScouts: Record<string, NPCScout>;
  /** Reports generated by NPC scouts, keyed by ID. */
  npcReports: Record<string, NPCScoutReport>;
  /** Scouting territories assigned to NPC scouts, keyed by ID. */
  territories: Record<string, Territory>;
  /** Countries active in the game world. */
  countries: string[];

  // --- Phase 2 extensions (stubbed for forward-compatibility) ---

  /** Financial tracking — income, expenses, equipment. */
  finances?: FinancialRecord;
  /** Narrative events that have occurred. */
  narrativeEvents: NarrativeEvent[];
  /** Rival scouts competing with the player. */
  rivalScouts: Record<string, RivalScout>;
  /** Tools unlocked by the player. */
  unlockedTools: ToolId[];
  /** Manager profiles per club (manager scouting preferences). */
  managerProfiles: Record<string, ManagerProfile>;

  // --- Phase 3 extensions (stubbed) ---

  /** Current transfer window state. */
  transferWindow?: TransferWindowState;
  /** Pre-defined season calendar events. */
  seasonEvents: SeasonEvent[];
  /** Daily schedule (used during transfer windows). */
  dailySchedule?: DaySchedule;

  // --- Phase 4 extensions (stubbed) ---

  /** Records of player discoveries and their career trajectories. */
  discoveryRecords: DiscoveryRecord[];
  /** Historical performance snapshots for analytics. */
  performanceHistory: ScoutPerformanceSnapshot[];

  /**
   * Fixture IDs that the player has completed interactively via the MatchScreen.
   * Used by advanceWeek() to ensure the player scouts scheduled attendMatch
   * fixtures before the engine auto-simulates the week.
   */
  playedFixtures: string[];

  /** Player IDs bookmarked by the scout for quick access. */
  watchlist: string[];

  /** Hidden intel gathered from contacts, keyed by playerId. */
  contactIntel: Record<string, HiddenIntel[]>;

  // --- Youth Scouting System ---

  /** Unsigned youth players in the world, keyed by ID. */
  unsignedYouth: Record<string, UnsignedYouth>;
  /** Placement reports for unsigned youth, keyed by ID. */
  placementReports: Record<string, PlacementReport>;
  /** Gut feelings accumulated by the scout. */
  gutFeelings: GutFeeling[];
  /** Alumni records for placed youth. */
  alumniRecords: AlumniRecord[];
  /** Legacy score tracking placed youth career impact. */
  legacyScore: LegacyScore;
  /** Sub-regions for youth scouting depth, keyed by ID. */
  subRegions: Record<string, SubRegion>;
  /** IDs of players who have retired. */
  retiredPlayerIds: string[];

  /** Unix timestamp (ms) when this game save was created. */
  createdAt: number;
  /** Unix timestamp (ms) of the most recent save. */
  lastSaved: number;
  /** Total weeks played across all sessions for this save. */
  totalWeeksPlayed: number;
}

// =============================================================================
// NEW GAME CONFIG
// =============================================================================

export interface NewGameConfig {
  scoutFirstName: string;
  scoutLastName: string;
  scoutAge: number;
  specialization: Specialization;
  difficulty: "easy" | "normal" | "hard";
  worldSeed: string;
  /** Starting region for regional specialists. Optional for other specs. */
  region?: string;
  /** Countries to include in the game world. Defaults to ["england"]. */
  selectedCountries?: string[];
  /** Starting country for the scout. Defaults to first selected country. */
  startingCountry?: string;
  /** Scout's nationality (display/flavour field). */
  nationality?: string;
  /**
   * If set, the scout begins employed at this club (tier 2 club scout).
   * If omitted, the scout starts as a freelancer (tier 1).
   */
  startingClubId?: string;
  /** Player-allocated bonus skill points during scout creation. */
  skillAllocations?: Partial<Record<ScoutSkill, number>>;
}

// =============================================================================
// MATCH FOCUS
// =============================================================================

/**
 * A scout's focus selection for a specific player during a live match.
 * The lens determines which attribute domain the scout concentrates on.
 */
export interface FocusSelection {
  playerId: string;
  /** Phase indices (0-based) during which this player was actively focused. */
  phases: number[];
  /** The observational lens applied — narrows which attributes are revealed. */
  lens: "technical" | "physical" | "mental" | "tactical" | "general";
}

// =============================================================================
// UTILITY TYPES
// =============================================================================

/**
 * Partial map of attribute changes. undefined means "no change" for that key.
 * Used in development tick results and attribute delta calculations.
 */
export type AttributeDeltas = Partial<Record<PlayerAttribute, number>>;

/** A single club's row in a league standings table. */
export interface StandingEntry {
  clubId: string;
  played: number;
  won: number;
  drawn: number;
  lost: number;
  goalsFor: number;
  goalsAgainst: number;
  goalDifference: number;
  points: number;
}

// =============================================================================
// PHASE 1: NPC SCOUTS & TERRITORIES
// =============================================================================

/**
 * An NPC scout that the player manages at career tier 4+.
 * NPC scouts autonomously scout territories and generate reports.
 */
export interface NPCScout {
  id: string;
  firstName: string;
  lastName: string;
  /** NPC quality tier, 1–5. Higher = better reports. */
  quality: number;
  /** Which country/region this NPC is assigned to. */
  territoryId?: string;
  /** Specialization the NPC focuses on. */
  specialization: Specialization;
  /** Weekly salary cost. */
  salary: number;
  /** Fatigue 0–100. High fatigue degrades report quality. */
  fatigue: number;
  /** Number of reports submitted this season. */
  reportsSubmitted: number;
  /** Morale 1–10. Low morale → less productive. */
  morale: number;
}

/**
 * A report generated by an NPC scout. Simplified compared to player reports.
 */
export interface NPCScoutReport {
  id: string;
  npcScoutId: string;
  playerId: string;
  week: number;
  season: number;
  /** Quality of the report, 0–100. Driven by NPC quality and fatigue. */
  quality: number;
  /** Brief text summary of the player. */
  summary: string;
  /** NPC's recommendation level. */
  recommendation: "monitor" | "shortlist" | "pursue";
  /** Whether the player has reviewed this report. */
  reviewed: boolean;
}

/**
 * A scouting territory that can be assigned to NPC scouts.
 */
export interface Territory {
  id: string;
  name: string;
  country: string;
  /** League IDs accessible from this territory. */
  leagueIds: string[];
  /** How many NPC scouts can be assigned here simultaneously. */
  maxScouts: number;
  /** IDs of NPC scouts currently assigned. */
  assignedScoutIds: string[];
}

/**
 * A scouting directive from the manager — what the club wants scouted.
 */
export interface ScoutingDirective {
  id: string;
  /** What the manager is looking for. */
  type: ScoutingPriority;
  /** Position the club needs. */
  position?: Position;
  /** Age range preference. */
  ageRange?: [number, number];
  /** Budget ceiling for the target. */
  maxBudget?: number;
  /** Urgency level 1–5. Higher = more impactful on review. */
  urgency: number;
  /** Description of what the manager wants. */
  description: string;
  /** Week this directive was issued. */
  issuedWeek: number;
  /** Whether the scout has addressed this directive. */
  fulfilled: boolean;
}

export type ScoutingPriority =
  | "firstTeamReady"
  | "youthProspect"
  | "specificPosition"
  | "loanTarget"
  | "budgetOption"
  | "worldClass";

/**
 * The player's relationship with the club manager.
 */
export interface ManagerRelationship {
  /** Manager's name. */
  managerName: string;
  /** Relationship quality 0–100. */
  trust: number;
  /** How often the manager listens to recommendations. */
  influence: number;
  /** Manager's preferred scouting style. */
  scoutingPreference: ScoutingPreference;
  /** Meetings held this season. */
  meetingsThisSeason: number;
}

export type ScoutingPreference =
  | "dataFirst"
  | "eyeTest"
  | "balanced"
  | "resultsBased";

/**
 * A board-level directive for the scouting department (tier 5).
 */
export interface BoardDirective {
  id: string;
  /** What the board wants to achieve. */
  type: "expandTerritory" | "cutCosts" | "findWonderkid" | "buildPipeline" | "improveAccuracy";
  description: string;
  /** Season deadline. */
  deadline: number;
  /** Whether the directive has been completed. */
  completed: boolean;
  /** Reputation reward on completion. */
  rewardReputation: number;
  /** Reputation penalty on failure. */
  penaltyReputation: number;
}

/**
 * An active travel booking for international scouting.
 */
export interface TravelBooking {
  /** Destination country. */
  destinationCountry: string;
  /** Week the travel departs. */
  departureWeek: number;
  /** Week the scout returns. */
  returnWeek: number;
  /** Cost in game currency. */
  cost: number;
  /** Whether the scout is currently abroad. */
  isAbroad: boolean;
}

/**
 * Scout's reputation and familiarity with a specific country.
 */
export interface CountryReputation {
  country: string;
  /** Familiarity 0–100. Higher = better accuracy in this country. */
  familiarity: number;
  /** Number of reports submitted from this country. */
  reportsSubmitted: number;
  /** Number of successful finds from this country. */
  successfulFinds: number;
  /** Contacts established in this country. */
  contactCount: number;
}

// =============================================================================
// PHASE 2: SYSTEMS DEPTH
// =============================================================================

export type NarrativeEventType =
  | "rivalPoach"
  | "managerFired"
  | "exclusiveTip"
  | "debutHatTrick"
  | "targetInjured"
  | "reportCitedInBoardMeeting"
  | "rivalRecruitment"
  | "agentDeception";

export interface NarrativeEvent {
  id: string;
  type: NarrativeEventType;
  week: number;
  season: number;
  title: string;
  description: string;
  /** IDs of related entities (players, clubs, contacts). */
  relatedIds: string[];
  /** Whether this event has been acknowledged by the player. */
  acknowledged: boolean;
  /** Optional choices the player can make in response. */
  choices?: { label: string; effect: string }[];
  /** Index of the choice the player selected (undefined = no choice made). */
  selectedChoice?: number;
}

export interface FinancialRecord {
  /** Current balance. */
  balance: number;
  /** Monthly income (salary). */
  monthlyIncome: number;
  /** Monthly expenses breakdown. */
  expenses: Record<ExpenseType, number>;
  /** Equipment quality level 1–5. Higher = better observation quality. */
  equipmentLevel: number;
  /** History of transactions. */
  transactions: { week: number; season: number; amount: number; description: string }[];
}

export type ExpenseType =
  | "rent"
  | "travel"
  | "subscriptions"
  | "equipment"
  | "npcSalaries"
  | "other";

export interface RivalScout {
  id: string;
  name: string;
  /** Quality 1–5. Higher = more competitive. */
  quality: number;
  /** Specialization. */
  specialization: Specialization;
  /** Club the rival works for. */
  clubId: string;
  /** Players the rival is currently tracking. */
  targetPlayerIds: string[];
  /** Reputation 0–100. */
  reputation: number;
}

export type ToolId =
  | "videoEditor"
  | "dataSubscription"
  | "scoutingApp"
  | "travelPlanner"
  | "contactManager"
  | "reportTemplates"
  | "youthDatabase"
  | "performanceTracker"
  | "networkAnalyzer";

export interface ManagerProfile {
  clubId: string;
  managerName: string;
  preference: ScoutingPreference;
  /** How much weight the manager gives to scouting reports, 0–1. */
  reportInfluence: number;
  /** Tactical system preference. */
  preferredFormation: string;
}

// =============================================================================
// PHASE 3: POLISH & PERSISTENCE
// =============================================================================

export interface TransferWindowState {
  type: TransferWindowType;
  /** Whether the window is currently open. */
  isOpen: boolean;
  /** Week the window opens. */
  openWeek: number;
  /** Week the window closes. */
  closeWeek: number;
  /** How many urgent requests have been made this window. */
  urgentRequestCount: number;
}

export type TransferWindowType = "summer" | "winter";

export interface DaySchedule {
  week: number;
  season: number;
  day: number;
  /** 3 slots per day during transfer windows. */
  slots: (Activity | null)[];
}

export interface SeasonEvent {
  id: string;
  type: SeasonEventType;
  name: string;
  /** Week range when this event is active. */
  startWeek: number;
  endWeek: number;
  description: string;
}

export type SeasonEventType =
  | "preSeasonTournament"
  | "summerTransferWindow"
  | "winterTransferWindow"
  | "internationalBreak"
  | "endOfSeasonReview"
  | "youthCup";

// =============================================================================
// PHASE 4: LEGACY & ANALYTICS
// =============================================================================

/**
 * Tracks a player discovered by the scout across seasons.
 */
export interface DiscoveryRecord {
  playerId: string;
  /** Week and season when the scout first observed the player. */
  discoveredWeek: number;
  discoveredSeason: number;
  /** Player's CA at discovery. */
  initialCA: number;
  /** Player's PA at discovery (if known). */
  initialPA?: number;
  /** Snapshots of the player's career at end of each season. */
  careerSnapshots: CareerSnapshot[];
  /** Whether this was a wonderkid discovery. */
  wasWonderkid: boolean;
  /** Scout's prediction accuracy (set retroactively). */
  predictionAccuracy?: number;
  /** Club ID where an unsigned youth was placed (youth scouting). */
  placementClubId?: string;
  /** How the youth was placed (academy intake or youth contract). */
  placementType?: "academyIntake" | "youthContract";
  /** Week the placement occurred. */
  placementWeek?: number;
  /** Season the placement occurred. */
  placementSeason?: number;
  /** Career outcome classification set retrospectively. */
  careerOutcome?: "starPlayer" | "squadPlayer" | "released" | "retired";
}

export interface CareerSnapshot {
  season: number;
  clubId: string;
  currentAbility: number;
  position: Position;
  age: number;
}

export interface LeaderboardEntry {
  id: string;
  scoutName: string;
  /** Overall score combining multiple metrics. */
  score: number;
  /** End-of-season the entry was submitted. */
  season: number;
  reputation: number;
  totalDiscoveries: number;
  predictionAccuracy: number;
  /** Timestamp of submission. */
  submittedAt: number;
}

/**
 * Monthly snapshot of scout performance for analytics.
 */
export interface ScoutPerformanceSnapshot {
  season: number;
  week: number;
  /** Rolling accuracy metric. */
  accuracy: number;
  /** Cumulative reports submitted. */
  totalReports: number;
  /** Average report quality. */
  avgQuality: number;
  /** Discovery rate (discoveries / reports). */
  discoveryRate: number;
  /** Skill levels at this snapshot. */
  skills: Record<ScoutSkill, number>;
  /** Reputation at this snapshot. */
  reputation: number;
}

// =============================================================================
// YOUTH SCOUTING SYSTEM
// =============================================================================

export type YouthVenueType =
  | "schoolMatch"
  | "grassrootsTournament"
  | "streetFootball"
  | "academyTrialDay"
  | "youthFestival"
  | "followUpSession"
  | "parentCoachMeeting";

export interface UnsignedYouth {
  id: string;
  player: Player;
  visibility: number;      // 0-100
  buzzLevel: number;       // 0-100
  discoveredBy: string[];  // scout IDs
  regionId: string;        // sub-region ID
  country: string;
  venueAppearances: YouthVenueType[];
  generatedSeason: number;
  placed: boolean;
  placedClubId?: string;
  retired: boolean;
}

export interface PlacementReport {
  id: string;
  unsignedYouthId: string;
  targetClubId: string;
  scoutId: string;
  conviction: ConvictionLevel;
  clubResponse?: "pending" | "accepted" | "rejected" | "trial";
  placementType?: "academyIntake" | "youthContract";
  qualityScore: number;    // 0-100
  week: number;
  season: number;
}

export interface GutFeeling {
  id: string;
  playerId: string;
  narrative: string;
  triggerDomain: AttributeDomain;
  reliability: number;     // 0-1
  wasAccurate?: boolean;
  week: number;
  season: number;
}

export type AlumniMilestoneType =
  | "firstTeamDebut"
  | "firstGoal"
  | "internationalCallUp"
  | "wonderkidStatus"
  | "transfer";

export interface AlumniMilestone {
  type: AlumniMilestoneType;
  week: number;
  season: number;
  description: string;
  notified: boolean;
}

export interface AlumniRecord {
  id: string;
  playerId: string;
  placedClubId: string;
  currentClubId: string;
  milestones: AlumniMilestone[];
  careerSnapshots: CareerSnapshot[];
  placedWeek: number;
  placedSeason: number;
}

export interface LegacyScore {
  youthFound: number;
  firstTeamBreakthroughs: number;
  internationalCapsFromFinds: number;
  totalScore: number;
}

export interface SubRegion {
  id: string;
  name: string;
  country: string;
  familiarity: number;     // 0-100
}
